### ISSUE TITLE
pnpm unmet peer react@"17.x | 18.x": found 17.0.2

### ISSUE THREAD

**Issue by timglabisch** [preactjs/signals#102]
i tryed to install `"@preact/signals-react": "^1.0.0",` using `pnpm 7.11.0` and got the following error: 

```
.
└─┬ @preact/signals-react 1.0.0
  └── ✕ unmet peer react@"17.x | 18.x": found 17.0.2
```

so `17.0.2` should work fine?
i am not sure if its a pnpm bug but may you could change the peerDependencies in a way, that pnpm understands it.

**Comment by aaron-manning** [comment]
I had this issue with npm 8.11.0
had to use legacy peer deps option to get it to install

**Comment by rschristian** [comment]
Sorry about that, minor typo in the version range there.

Thanks for opening an issue!
