### ISSUE TITLE
First update doesn't work on Codesandbox (React version)

### ISSUE THREAD

**Issue by verekia** [preactjs/signals#107]
I don't have the issue when testing locally, but on Codesandbox, the counter goes from 0 to 2 (with the React version):

https://codesandbox.io/s/signals-issue-count-starts-at-2-03ec2u?file=/src/App.js

Possibly related to https://github.com/preactjs/signals/issues/79?

**Comment by elliotwaite** [comment]
I'm also seeing this behavior with the React version, even when testing locally.

**Comment by JoviDeCroock** [comment]
Duplicate of #79
