### ISSUE TITLE
A computed value is updated even when all of its dependencies haven't changed.

### ISSUE THREAD

**Issue by elliotwaite** [preactjs/signals#124]
From reading over the logic in [core](https://github.com/preactjs/signals/blob/main/packages/core/src/index.ts), I think I found something that could go wrong. I created this test, which currently isn't passing, to illustrate the issue:
```
it("should not update a sub if all deps unmark it", () => {
    // In this scenario "B" and "C" always return the same value. When "A"
    // changes, "D" should not update.
    //     A
    //   /   \
    // *B     *C
    //   \   /
    //     D
    const a = signal("a");
    const b = computed(() => {
        a.value;
        return "b";
    });
    const c = computed(() => {
        a.value;
        return "c";
    });
    const spy = sinon.spy(() => b.value + " " + c.value);
    const d = computed(spy);
    expect(d.value).to.equal("b c");
    spy.resetHistory();

    a.value = "aa";
    expect(spy).not.to.be.called; // <- this assertion currently does not pass.
});
```

What I think happens is that when `a` is updated, it calls `mark` recursively down the tree starting at `a` resulting in:
```
a._pending = 1
b._pending = 1
c._pending = 1
d._pending = 2
```
Then, the `sweep` starts at `a`, then goes to `b` where it calls `b`'s `_updater` which recomputes `b` and since its value is the same, it calls unmark on `b`'s subs which are `d`, and in that `unmark` for `d` it decrements `d._pending` bringing it to 1. Then were back in the `sweep` call for `b` and we call `sweep` on all of `b`'s subs, which is `d`. So then in the `sweep` call for `d` the `if (--signal._pending === 0) {` condition decrements `d._pending` to 0 and evaluates to `true`, which causes `d` to recompute unnecessarily.

At least that's what I think is happening from reading the code. I haven't checked it with a debugger.

The issue seems to be related to the fact that both `unmark` and `sweep` can decrement the `_pending` value, and a node that returns the same value can both `unmark` its subs and then `sweep` its subs, which can double decrement their `_pending` value, which I would think is unintended, but I'm not quite sure, I'm still trying to wrap my head around this code.

Is the intended mark and sweep algorithm a standard one that I could read more about somewhere, or is the specific algorithm that is used somewhat unique?

I haven't thought too much about a solution to this issue yet, since I figured those more familiar with the code and the intended algorithm would have a better idea of what to change, but I'd be open to working on a solution if help in that area is wanted.

**Comment by marvinhagemeister** [comment]
That's a good one, thanks for reporting it 👍 

The current algorithm is basically a topological sort on the state graph which can be thought of as a directed acyclic graph (DAG). We really want to replace the `_pending` counter logic with a different algorithm that uses a different mechanism for ordering. It's something we didn't get around to for the initial release.
