### ISSUE TITLE
@preact/signals-react crashes on production build, at least using `react-scripts build`

### ISSUE THREAD

**Issue by calebgregory** [preactjs/signals#125]
cf: https://github.com/preactjs/signals/issues/86

The error here is:  `TypeError: Invalid value used as weak map key`

![image](https://user-images.githubusercontent.com/10540157/189553177-eed136a5-d331-4dad-98a6-b51fb68e8552.png)

What appears to be the case is that `internals.ReactCurrentOwner.current` is not set.

Here are the versions I have installed:
```
    "@preact/signals-react": "^1.0.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "typescript": "^4.4.2",
```
and the browser configuration:
```
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
```

### How to reproduce:

1. using `create-react-app` (`typescript` template), create a react app
2. use `@preact/signals-react`
3. `yarn build` (creates a production build)
4. open your built browser-app in the browser
5. behold this error

**Comment by izznatsir** [comment]
It also crashes when building using Vite.

**Comment by marvinhagemeister** [comment]
This PR isn't in `@preact/signals-react 1.0.1`. It will be in the next version which I'm just in the process of publishing.

**Comment by dackom** [comment]
So sorry for bothering you guys again... 
With react-signals 1.0.2 build for production is now working, but looks like that signals itself is not working at all. At least in my scenario, using it with context. 

Firebase onAuthStateChange:

```
onAuthStateChanged(
    auth,
    (u) => {
      console.log("AUTH STATE CHANGED", u);
      user.value = u; // <-- nothing happens when this is set
    }
  );
```
On dev production it works ok. Could it be that vite is building react in strict mode and that first re-render with signal is not working.

**Comment by dackom** [comment]
Yeah, I just tested it... So the most simple example:

```
const count = useSignal(1);
return (
<div>
   {count}
   <button onClick={() => count.value++}>INC</button>
</div>
);
```

Is not working when you build it for production for react. In dev mode it's working ok.

**Comment by Niscolinx** [comment]
Were you able to resolve it

**Comment by noopurphalak** [comment]
@dackom Were you able to resolve it?

**Comment by dackom** [comment]
At the end, I rewrote app with context and usestate. But this is probably fixed in some newer versions.
