### ISSUE TITLE
Errors when Using Signals in React 

### ISSUE THREAD

**Issue by 18121A05L2** [preactjs/signals#138]
hey , i am new to signals . today I just tried @preact/signals-react . in UI it is working fine in updating values but i am getting an error in the console when importing import { signal } from "@preact/signals-react"; 

you can check the error in the image below

![Screenshot (4322)](https://user-images.githubusercontent.com/59156926/189963228-2a4dac73-4a03-4cdb-9f7b-aff427df449f.png)

**Comment by marvinhagemeister** [comment]
Huh that looks strange. Looks like something is crashing in the error overlay.

**Comment by TiavinaRakotobe** [comment]
I got the same problem but I was able to fix it by fixing react/jsx-key errors, I dunno why

**Comment by JoviDeCroock** [comment]
As we are pushing people towards [the Babel plugin](https://github.com/preactjs/signals/tree/main/packages/react-transform) and away from the automatic runtime I’ll close this issue.
