### ISSUE TITLE
Signals do not work when used as attribute values on SVG elements

### ISSUE THREAD

**Issue by high1** [preactjs/signals#181]
Tried something like this:
```
import type { ReadonlySignal } from '@preact/signals';
import type { JSX } from 'preact';

type HandProps = {
  length: number;
  limit?: number;
  stationary?: boolean;
  transform: ReadonlySignal<string>,;
} & Omit<JSX.SVGAttributes<SVGLineElement>, 'transform'>;

export const Hand = ({
  className = '',
  length = 0,
  limit = 90,
  stationary,
  transform,
  ...rest
}: HandProps) => (
  <line
    className={`stroke-cap-round ${className}`}
    transform={transform}
    y1={stationary ? length - limit : undefined}
    y2={-(stationary ? limit : length)}
    {...rest}
  />
);
```
but it doesn't work. I know the support is still experimental, just wanted to report this, as this works for other elements, I'm seeing this on SVG elements. TypeScript will show an error, but I think there's an issue regarding that.

**Comment by JoviDeCroock** [comment]
Mind defining "doesn't work", are you referring to the TypeScript issue or the attributes aren't being set?

**Comment by high1** [comment]
It does not work, attributes are not being set - sorry if the issue was unclear.

**Comment by marvinhagemeister** [comment]
Can confirm. I was able to reproduce the bug on my end.
