### ISSUE TITLE
Consider implementing `untrack` or allow value updates without subscribing

### ISSUE THREAD

**Issue by dminikm** [preactjs/signals#189]
Since accessing `.value` of a signal subscribes to any future updates, this can cause some unwanted rerunning of effects/infinite render loops.

I think it would be a good idea to implement a way to read and update the value without triggering a subscription. One way to solve this would be with something like `untrack`. This would be a function similar to effect:

```js
effect(() => {
  const value = signal1.value                      // Triggers reactivity when signal1 changes
  untrack(() => signal2.value += value)     // Updates signal2, but does not trigger when signal2 changes
})
```

The other way I can think of is by adding a `update` function to a signal:

```js
effect(() => {
  signal2.update((s2) => s2 + signal1.value) // signal1 triggers effect, but signal2 doesn't
})
```

**Comment by jviide** [comment]
Would `.peek()` help here? https://github.com/preactjs/signals#signalpeek

**Comment by dminikm** [comment]
@jviide `peek` is used for reading a signals value without subscribing to it. I'm proposing a way to update a signals value without subscribing to it.

**Comment by jviide** [comment]
Ah, right. Effects shouldn't subscribe to signals whose values are _only_ set inside the effect - so for example in this example the effect does subscribe to `a` but not `b`:

```ts
const a = signal(0);
const b = signal(0);

effect(() => {
  b.value = a.value;
});
```

However, there are some patterns that kinda look like only updates, but actually access the value too. I've been bit several times by the fact that the effect _does_ subscribe to `a` here:

```ts
const a = signal(0);

effect(() => {
  a.value++; // equal to a.value = a.value + 1, so the `a.value` is also read and therefore subscribed
});
```

**Comment by dminikm** [comment]
@jviide You were right. That did indeed fix the issue I was having. I guess that's what I get for just skimming through the docs.

**Comment by jviide** [comment]
Awesome that it got solved 👍
