### ISSUE TITLE
Unmounting throws in SSR

### ISSUE THREAD

**Issue by matthewp** [preactjs/signals#197]
When used with `preact-render-to-string` and unmounting a vnode it throws here: https://github.com/preactjs/signals/blob/322371b58af4519f3e0a3c8d3896566543acee85/packages/preact/src/index.ts#L255 because `__e` is null.

Noticed that another hook checks to see if it exists: https://github.com/preactjs/signals/blob/322371b58af4519f3e0a3c8d3896566543acee85/packages/preact/src/index.ts#L175

So I'm guessing the problem is just with the unmount hook?

**Comment by marvinhagemeister** [comment]
@matthewp Thanks for reporting this issue. We'll cut a new release in a bit.

**Comment by marvinhagemeister** [comment]
@matthewp Alright, fix [is published](https://github.com/preactjs/signals/releases/tag/%40preact%2Fsignals%401.1.1) as `@preact/signals v1.1.1`

**Comment by matthewp** [comment]
Thank you @marvinhagemeister and @JoviDeCroock !
