### ISSUE TITLE
Error In Production

### ISSUE THREAD

**Issue by jaskaur18** [preactjs/signals#211]
<img width="1221" alt="image" src="https://user-images.githubusercontent.com/51957556/192128131-b20bd863-af9d-42bc-844c-dcb1cbd6ff8b.png">

Electron + Vite + React

Template - https://github.com/electron-vite/electron-vite-react

Work Fine In Dev but when build it doesn't

**Comment by rschristian** [comment]
Maybe a duplicate of #155?

**Comment by pacholoamit** [comment]
I'm still trying to resolve this, I got `signals` to work just fine for React & Vite while running while using the development server but whenever I build to production, `signals` don't seem to render correctly. I wonder if this issue is specific to `vite`

**Comment by ARival** [comment]
@pacholoamit I get the exact same error using React + NextJS on production builds.

**Comment by pacholoamit** [comment]
@ARival , I see. Yeah, It's such a shame since I adopted `signals` and wrote a lot of state code with it. Only to have issues when building for production. I transitioned back to good ol' `useState` for local state and `React context` for global state.

**Comment by FrancocDev** [comment]
I think that is a problem with Vite.
In dev all work correctly but on production, the React app didn't render correctly.

**Comment by pacholoamit** [comment]
I tried compiling a production build with ReactJS + Vite + Tauri with the [new realease](https://github.com/preactjs/signals/releases/tag/%40preact%2Fsignals-react%401.1.1) v1.1.1 of signals and signals is now working with production builds with ReactJS + Vite.

**Comment by marvinhagemeister** [comment]
Closing as I can't reproduce that with the latest signals release anymore 🎉
