### ISSUE TITLE
Is signal core working with Solidjs?

### ISSUE THREAD

**Issue by CKGrafico** [preactjs/signals#223]
I've tried Signal succesfully with Angular and React, now I'm testing with  Solidjs and looks not rerendering, am I doing something wrong?

https://codesandbox.io/s/solidjs-starter-template-forked-mtj8qz?file=/src/App.js

**Comment by high1** [comment]
Core will not work on it's own with Solid, Solid doesn't track signals, only it's own primitives. In your codesanbox, it's enough to just wrap the signal inside a mutable, to make it work.
`const initials = createMutable(() => signal("test"));`

**Comment by rschristian** [comment]
You're not doing anything wrong, no, but there's probably a misunderstanding here in how the pieces fit together.

Signal's core is just for creating/handling the state primitive. Allows to get/set values, form computed values, etc. This will only work in vanilla JS or any framework that does not require a specific API for triggering rerenders (like Svelte). The Preact & React integrations therefore exist to fix this "issue" and offer APIs to trigger rerenders as setting a new value for a signal will not.

As mentioned, Solid does not rerender components. Instead, Solid updates the value in place allowing it to skip the parts of the component that stayed the same, similar to the rendering optimizations that signals can provide in Preact.

**Comment by marvinhagemeister** [comment]
Closing, since there is nothing for us to do here. Like others said: Solidjs uses a different primitive than Signals and it's one can convert between them via a `createMutable`.
