### ISSUE TITLE
Can't use signal in JSX props directly

### ISSUE THREAD

**Issue by HoikanChan** [preactjs/signals#224]
Hi, I wondering how to use signal in JSX props. 
When I play with the react demo in the repo, here is my code.
```jsx
const sig = signal(0);

function App() {
  return <input className={sig} value={sig}  onChange={() => { sig.value++ }}/>
}
```
**`value` can update while `className` can't**

I found there is a monkey patch for `React.createElement` but not for [the new JSX transform](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html)? Maybe the missing patch for new JSX transform cause this issues (The demo's  JSX config  is "automatic" now )
```js
esbuild: {
  jsx: "automatic",
  jsxImportSource: "react",
},
```

**Comment by HoikanChan** [comment]
I check the fiber of input, the values in  `memoizedProps` and `pendingProps`  are Signal.
:rofl:  How can React take the Signal object and render the value properly?  What's more,  the value can update after the signal update!!
**Signal is amazing**

**Comment by marvinhagemeister** [comment]
The prop bindings are only properly supported in Preact. There are attempts to bring that to React but that's much more difficult as their renderer isn't as extensible as Preact's.

**Comment by JoviDeCroock** [comment]
This is fixed on latest https://codesandbox.io/s/elegant-matsumoto-rulyy8?file=/src/App.js
