### ISSUE TITLE
React package seems to violate the rules of hooks

### ISSUE THREAD

**Issue by sbesh91** [preactjs/signals#229]
I'm using the react signals package for a very small portion of our application.  The screenshot below shows a portion of our app that doesn't interact with signals at all, but now throws this error when signals is imported elsewhere in our bundle.  Our app is currently on react 17 not in strict mode.  In production we saw this error reported as https://reactjs.org/docs/error-decoder.html/?invariant=321
![](https://user-images.githubusercontent.com/3409138/193656539-7074dedb-6435-4ab9-8063-dff32b3e8b8a.png)

**Comment by Emanuelcarvalho2004** [comment]
Humm

**Comment by marvinhagemeister** [comment]
Fixed by #219
