### ISSUE TITLE
Error [ERR_UNSUPPORTED_DIR_IMPORT] during `next build`

### ISSUE THREAD

**Issue by nnaucorp** [preactjs/signals#237]
When I try to build my next js app, the build got failed due to `ERR_UNSUPPORTED_DIR_IMPORT`.
Here is the complete log of the build.

![image](https://user-images.githubusercontent.com/81728705/195764748-1189a8a0-2ef4-4ff0-975b-618d9521c0c3.png)

nextjs: 12.3.1
react: 18.2.0
@preact/signals-react: 1.2.0

**Comment by Nayeem-XTREME** [comment]
https://github.com/preactjs/signals/actions/runs/3252211104
@marvinhagemeister

**Comment by marvinhagemeister** [comment]
FYI: Just cut a new release with the fix 🎉
