### ISSUE TITLE
Relationship to Incremental Computation

### ISSUE THREAD

**Issue by rkirov** [preactjs/signals#239]
Hello,

Great work on this project! I am wondering if you are aware of the research area of `incremental computation` in computer science, and whether it influenced it project. The gist of it is that at some point researchers were interested whether one can easily (automatically?) take any computation (but mostly algorithmic examples) and generate an incremental version of the computation. Incremental meaning when some inputs to the computation change the outcome can "react", i.e. update in a way more efficient than recomputation. AFAIKT, theoretical interest has fizzled out since early 2000s. 
Some papers [here](https://software.imdea.org/~rleywild/publications/afp08/afp08.pdf) and [here](https://www.researchgate.net/publication/221241270_Monads_for_incremental_computing) and many more references to follow around the same authors.

Meanwhile, computing UIs is just one particular type of computation that we have put a lot of effort in JS-land to make efficient through incrementally. Kudos the preact team for splitting the incremental core (signals here) vs the application to DOM computation (in rest of preact).

This means that the signals library can be used to create incremental algorithms in any domain (not just UIs). Here is an example how todo quick sort using it - https://replit.com/@RadoslavKirov/incremental-quick-sort-with-signals?v=1. Have you seen any non-UI applications of this library?

My own exploration of bringing those ideas to JS is https://github.com/rkirov/adapt-comp, but signals offers a much more ergonomic API.

P.S. Feel free to close this issue, it is just a conversation starter.

**Comment by marvinhagemeister** [comment]
Thanks for the kind words!

As far as I'm aware we didn't look at any paper in particular, but the general idea of incremental computation or reactivity has been on everyone's mind for a while. They are a really great fit for building UIs and we're certainly not the first ones to choose that path.

> Have you seen any non-UI applications of this library?

Haven't seen signals specifically used for that in the wild yet, but I think that will come. There is already a lot of rxjs usage in node servers, so the concept is definitely there. Used signals myself in one of my recent explorations to wire up playwright inside jest and to coordinate generating bundles for that on the fly.
