### ISSUE TITLE
The need for using context for global state

### ISSUE THREAD

**Issue by kevinschaffter** [preactjs/signals#254]
I noticed in the docs there was mention of passing around signals via context and props. Just curious as to why it wouldn't be possible to just have the signals defined in a file that gets imported by the respective components that need to access them? I'm sure I'm probably missing something but would appreciate any guidance!

**Comment by marvinhagemeister** [comment]
I don't think we have anything in our docs that says that just using global signals and importing them where needed isn't possible. In fact the examples in the introduction blog post uses that pattern extensively. It's a perfectly fine pattern to use for smaller apps.

The only reason one might want to go with context instead is if you have multiple instance of your app running at the same time with different state. Some testing setups do that.

**Comment by kevinschaffter** [comment]
Thanks for the response. What confused me is the wording of this statement. Without much context the wording seemed to suggest that context was the means for global app state 

> This works in our todo list app because the state is global, however larger apps typically end up with multiple components that require access to the same pieces of state. This usually involves "lifting state up" to a common shared ancestor component. **To avoid passing state manually through each component via props, the state can be placed into [Context](https://preactjs.com/guide/v10/context) so any component in the tree can access it.** Here is a quick example of how that typically looks:

Also:

> The majority of application state ends up being passed around using props and context.
