### ISSUE TITLE
Typescript error when passing signal directly into JSX

### ISSUE THREAD

**Issue by kevinschaffter** [preactjs/signals#261]
When passing a signal directly into JSX in an attempt to bypass VDOM leads to the below TS error. It does work as expected from a functional standpoint however.

`Type 'ReadonlySignal<string>' is not assignable to type 'ReactNode'.ts`

<img width="665" alt="Screen Shot 2022-11-03 at 10 13 50 PM" src="https://user-images.githubusercontent.com/27298326/199877225-0c25acf2-1984-48df-adf2-6944c8136af1.png">

`"@preact/signals-react": "^1.2.1"`
`"@types/react": "^18.0.24"`

Just wondering what the recommended approach is around this? Thank you!

**Comment by yoroshikun** [comment]
I was under the impression that this was a preact adapter only optimisation, that is not present in react. But it would be nice to have in react.
https://github.com/preactjs/signals/blob/main/packages/preact/README.md#rendering-optimizations

**Comment by cafreeman** [comment]
@yoroshikun it works in React today, the types just don't line up.
