### ISSUE TITLE
What does this test do?

### ISSUE THREAD

**Issue by elliotwaite** [preactjs/signals#264]
I was reading over the tests for the core package and I saw [this test](https://github.com/preactjs/signals/blob/main/packages/core/test/signal.test.tsx#L979) that I didn't understand:

```
	it("should consider undefined value separate from uninitialized value", () => {
		const a = signal(0);
		const spy = sinon.spy(() => undefined);
		const c = computed(spy);

		expect(c.value).to.be.undefined;
		a.value = 1;
		expect(c.value).to.be.undefined;
		expect(spy).to.be.calledOnce;
	});
```
Why is the `a` signal created and assigned to (it seems like that shouldn't have any effect)? Also, which value is the uninitialized value, and how does this test show that an undefined value is considered separate from an uninitialized value? I wasn't sure if I just didn't understand the test or if there was a bug in it, so I thought I'd ask about it here.

**Comment by developit** [comment]
Looks like a bug in that test. I believe it should be asserting that the computed's value is considered unchanged when repeatedly `undefined`, though in the current implementation that would never happen anyway.

```js
	it("should not consider undefined value separate from uninitialized value", () => {
		const a = signal(0);
		const bSpy = sinon.spy(() => (a.value, undefined));
		const b = computed(spy);
		const cSpy = sinon.spy(() => b.value);
		effect(cSpy);

		expect(b.value).to.be.undefined;
		a.value = 1;
		expect(b.value).to.be.undefined;
		expect(bSpy).to.be.calledTwice;
		expect(cSpy).to.be.calledOnce;
	});
```

**Comment by elliotwaite** [comment]
Ah, got it. That makes more sense. Thanks for the clarification.
