### ISSUE TITLE
Using signals without NPM module

### ISSUE THREAD

**Issue by urizev** [preactjs/signals#275]
Hi,

Currently I am using Preact by importing it in the web browser like this:

    <script src="https://unpkg.com/preact" />

And I would like to integrate signal in my application. I am looking for signals in unpkg but I cannot find it.

**Comment by rschristian** [comment]
Unpkg consumes from NPM, meaning every package is named the same.

`@preact/signals` -> https://unpkg.com/browse/@preact/signals/

**Comment by urizev** [comment]
Great! Thanks!
