### ISSUE TITLE
Bug: signals aren't reactive on lazy imported components

### ISSUE THREAD

**Issue by waelbettayeb** [preactjs/signals#301]
Signals aren't reactive on lazy imported components on the react version. However, in the preact experiment suspense works fine.

**Comment by englishisnotenglish** [comment]
same issue

**Comment by agileago** [comment]
same +1

**Comment by loicnestler** [comment]
Any updates on this?

**Comment by ywang1724** [comment]
same +1

**Comment by andrewiggins** [comment]
Could someone provide a minimal repro of the issue? Is this using react or preact package? What versions, etc. etc.

**Comment by ywang1724** [comment]
> Could someone provide a minimal repro of the issue? Is this using react or preact package? What versions, etc. etc.

hi~, @andrewiggins , you can reproduce it with this [demo](https://github.com/ywang1724/signals-app-demo).

A few points:

- react@18.2.0
- @preact/signals-react@1.2.2

Steps to reproduce:

1. Run `pnpm i && pnpm dev`;
2. Visit page: http://localhost:5173, and click the button;
3. You can see this phenomenon: the signal named count, its value changes and the direct imported component follow the changes,  but the lazy imported component did not follow.

**Comment by XantreGodlike** [comment]
#420 it also is not working with forward refs

**Comment by mendrik** [comment]
same problem with react.signals in 2.2.0 + @preact/signals-react-transfor:  0.4.0

**Comment by JoviDeCroock** [comment]
As we are pushing people towards [the Babel plugin](https://github.com/preactjs/signals/tree/main/packages/react-transform) and away from the automatic runtime I’ll close this issue.
