### ISSUE TITLE
Problem with react-router-dom

### ISSUE THREAD

**Issue by StephenSHorton** [preactjs/signals#314]
Reproduction: [CodeSandbox](https://codesandbox.io/s/signals-issue-with-react-router-dom-6n91dx?file=/src/App.tsx)

Error
```
[Route] is not a <Route> component. All component children of <Routes> must be a <Route> or <React.Fragment>
```

**Comment by rschristian** [comment]
Duplicate of #251, from the looks of it

**Comment by StephenSHorton** [comment]
Looks like this is a duplicate! Thanks @rschristian
