### ISSUE TITLE
useSignalEffect doesn't accept dependencies

### ISSUE THREAD

**Issue by jamesarosen** [preactjs/signals#326]
I have a non-Signal dependency that I want to use in a Signal callback. I tried this:

```ts
function useMyHook(foo: Signal<Foo>, bar: Bar) {
  useSignalEffect(() => {
    return foo.subscribe(() => console.log(foo.value, bar))
  })
}
```
The `bar` never updates because `useSignalEffect` hides the dependency. I can't even pass it explicitly. This produces a TypeError:

```ts
function useMyHook(foo: Signal<Foo>, bar: Bar) {
  useSignalEffect(() => {
    return foo.subscribe(() => console.log(foo.value, bar))
  }, [bar])
}
```

The only solution is to use `subscribe` and `useEffect` to combine the two:

```ts
function useMyHook(foo: Signal<Foo>, bar: Bar) {
  useEffect(() => {
    return foo.subscribe(() => console.log(foo.value, bar))
  }, [bar, foo]) // foo itself will never change; we add it to make ESLint happy
}
```

**Comment by jamesarosen** [comment]
There are _many_ libraries that are not signal-based. It's absolutely fine to have the opinion that a signals-based app should wrap each of those in signal-awareness. This is what is required for that wrapping.

**Comment by jamesarosen** [comment]
Or is the solution a documentation change rather than a code change? Perhaps a guide on integrating Signals with non-signals code.

**Comment by lsimone** [comment]
@jamesarosen I had the same problem and I solved in a few lines of code.

Since I have changes that react `useEffect` would "see" but `useSignalEffect` does not, I thought the only way to deal with this use case is to "`signalify`" dependencies.

```ts
/**
 * It creates a signal that tracks the value of a prop.
 * Whenever the prop changes, the signal value is updated.
 * This is useful when effects or computed depend on a prop
 * because they would not be triggered on prop change.
 * @param prop
 * @returns
 */
export const useTrack = <T>(prop: T) => {
  const sig = useSignal(prop)
  useEffect(() => {
    sig.value = prop
  }, [prop])
  return sig
}
```

I am currently using it in my app and solved the problem so I guess it would solve yours too:

```ts
function useMyHook(foo: Signal<Foo>, bar: Bar) {
  const barSignal = useTrack(bar)
  useSignalEffect(() => {
    return foo.subscribe(() => console.log(foo.value, barSignal.value))
  })
}
```

LMK if this helps :wink:

**Comment by rschristian** [comment]
Going to close this out. 

As Jovi mentioned, `effect`, `useSignalEffect`, etc. apply side effects to signal changes. They're not for applying side effects to any ol' piece of data changing.
