### ISSUE TITLE
Why my ComponentDidMount lifecycle are trigger twice ?

### ISSUE THREAD

**Issue by dc198689** [preactjs/signals#329]
Hi, I have a issue and hope someone to help fix.
- React v16.8.6
- @preact/signals-react v1.2.2

My useEffect (ComponentDidMount) are trigger twice when page load !!
P.S I found that if I removed the import { signal } from '@preact/signals-react', thats work for me. I want to use @preact/signals-react tools.

`
import React, { useEffect } from 'react';
import { signal } from '@preact/signals-react';

const Scenes = (props) => {

    useEffect(() => {
        console.log('ComponentDidMount'); // Trigger Twice !!
    }, []);

    return <div>Hello</div>;

}
export default Scenes;
`

**Comment by JoviDeCroock** [comment]
Your effect had no dependencies and you might have strict mode on

**Comment by dc198689** [comment]
> P.S I found that if I removed the import { signal } from '@preact/signals-react', thats work for me. I want to use @preact/signals-react tools.

P.S I found that if I removed the import { signal } from '@preact/signals-react', thats work for me. I want to use @preact/signals-react tools.

I pretty sure I have not use the StrictMode of my react version

**Comment by rschristian** [comment]
Going to close this out. As mentioned, you probably have strict mode on which would cause this behavior.
