### ISSUE TITLE
Typescript errors when using signals directly in jsx

### ISSUE THREAD

**Issue by joetifa2003** [preactjs/signals#332]
![image](https://user-images.githubusercontent.com/62658783/228066435-e38054c3-6177-4db3-a5aa-362ce7c98671.png)

**Comment by joetifa2003** [comment]
This and the hot reloading not working are the only things that keeping me from using this fantastic library.

**Comment by suchangv** [comment]
Maybe you should use `count.value` and `doubled.value`.

**Comment by LucasCNordstrom** [comment]
I fixed it by writing 'signal as unknown as number'. This is the equivalent of using : any. But it works until this issue is fixed. In your example- 
<div>{count as unknown as number}</div>

**Comment by joetifa2003** [comment]
Hey, any update on this, Thanks!

**Comment by rschristian** [comment]
I believe #271 corrected this
