### ISSUE TITLE
feature: Lit integration

### ISSUE THREAD

**Issue by willmartian** [preactjs/signals#337]
It would be nice for Preact signals to integrate with Lit and `lit-html`. I think it would be a fairly light wrapper, involving their [async directive.](https://lit.dev/docs/templates/custom-directives/#async-directives) 

I did some experimentation with a similar concept [here. ](https://github.com/willmartian/lit-signals) Thoughts? Can I open a PR? :)

**Comment by rschristian** [comment]
> Can I open a PR? :)

Absolutely! More tools supported the better!

**Comment by rschristian** [comment]
Looks like Lit has created their own signals integration, which can be found here: [`@lit-labs/preact-signals`](https://www.npmjs.com/package/@lit-labs/preact-signals)

Going to close this on out
