### ISSUE TITLE
Basic example does not work

### ISSUE THREAD

**Issue by jboolean** [preactjs/signals#338]
The [basic counter example](https://preactjs.com/repl?code=import%20%7B%20render%20%7D%20from%20%22preact%22%3B%0A%0Aimport%20%7B%20signal%20%7D%20from%20%22%40preact%2Fsignals%22%3B%0A%0A%2F%2F%20Create%20a%20signal%20that%20can%20be%20subscribed%20to%3A%0Aconst%20count%20%3D%20signal(0)%3B%0A%0Afunction%20Counter()%20%7B%0A%20%20%2F%2F%20Accessing%20.value%20in%20a%20component%20automatically%20re-renders%20when%20it%20changes%3A%0A%20%20const%20value%20%3D%20count.value%3B%0A%0A%20%20const%20increment%20%3D%20()%20%3D%3E%20%7B%0A%20%20%20%20%2F%2F%20A%20signal%20is%20updated%20by%20assigning%20to%20the%20%60.value%60%20property%3A%0A%20%20%20%20count.value%2B%2B%3B%0A%20%20%7D%0A%0A%20%20return%20(%0A%20%20%20%20%3Cdiv%3E%0A%20%20%20%20%20%20%3Cp%3ECount%3A%20%7Bvalue%7D%3C%2Fp%3E%0A%20%20%20%20%20%20%3Cbutton%20onClick%3D%7Bincrement%7D%3Eclick%20me%3C%2Fbutton%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20)%3B%0A%7D%0A%0Arender(%3CCounter%20%2F%3E%2C%20document.getElementById(%22app%22))%3B%0A) in the documentation, when run in the REPL, does not count.

I am trying to use signals for the first time and I similarly cannot get something really basic to work. Is this library totally borked?

**Comment by jboolean** [comment]
Okay, I "solved" it. The REPL can be fixed by adding a version specifier to the signals import, such as "@preact/signals@1.1.1"

My app was fixed by not using the htm/preact/standalone combo import of htm+preact, and adding a version specifier to the signals import.

Something is very strange here.

**Comment by rschristian** [comment]
For issues with the REPL, please track this issue: https://github.com/preactjs/preact-www/issues/978

We borked our REPL, it's not an issue with the library.

> My app was fixed by not using the htm/preact/standalone combo import of htm+preact, and adding a version specifier to the signals import.
>
> Something is very strange here.

This is correct behavior. Like hooks. signals rely upon Preact being a singleton (loaded once). It's very easy for CDNs to load multiple copies accidentally, i.e., `htm/preact/standalone` drags in one copy, and `@preact/signals` (can) drag in another. You need to ensure everything resolves to the same version so you don't get multiple copies.

See https://github.com/preactjs/signals/issues/303#issuecomment-1429555727
