### ISSUE TITLE
Bug: TypeError: setting getter-only property "className"

### ISSUE THREAD

**Issue by ShivamJoker** [preactjs/signals#340]
I am trying to derive `className` based on the signal state but, without using the `value` I am unable to achieve it.

```js
Uncaught (in promise) TypeError: setting getter-only property "className"
    Preact 13
    compareSignatures index.js:13
    flush index.js:23
    flush index.js:22
    <anonymous> Button.tsx:34
```

Here is my component:

```tsx
import { computed, effect, Signal } from "@preact/signals";
import { HTMLAttributes } from "preact/compat";

interface Props extends HTMLAttributes<HTMLButtonElement> {
  label: string;
  variant?: "primary" | "secondary";
  isLoading?: Signal<boolean>;
}

const Button = ({
  label,
  isLoading,
  className,
  variant = "primary",
  ...rest
}: Props) => {
  console.log("button rendered");

  const btnLabel = computed(() => (!isLoading?.value ? label : ""));
  const btnClass = computed(
    () =>
      `btn ${variant} ${isLoading?.value ? "btn-loading" : ""} ${
        className ?? ""
      }`
  );
  return (
    <button className={btnClass} {...rest}>
      {btnLabel}
    </button>
  );
};

export default Button;
```

**Comment by funkyOne** [comment]
Not sure it's the main reason, but you should use `useComputed` (not `computed`) within a component.

**Comment by ShivamJoker** [comment]
> Not sure it's the main reason, but you should use `useComputed` (instead of `computed`) within a component.

That didn't change anything.

**Comment by andrewiggins** [comment]
What version of Preact are you using? If it is not the latest (10.13.2 as of writing), could you try with that version? There was a change related to compat's handling of `class` and `className` and I'm curious if that might be either the cause or fix for the error you see here.

**Comment by ShivamJoker** [comment]
I updated to the latest version it seems to fix the issue.
Also used `useComputed`

Thanks a lot.
