### ISSUE TITLE
Implement `untrack` to get multiple values of different signals without subscribing to them

### ISSUE THREAD

**Issue by fabian-hiller** [preactjs/signals#349]
Hi, I am the author of [Modular Forms](https://modularforms.dev/guides/introduction) and I am toying with the idea of making my form library available for Preact as well.

Modular Forms uses only Signals internally to manage state. This allows us to basically plug in almost any UI library that supports Signals by putting the Signals in a consistent format internally. This allows us to offload the core form logic into a separate package and implement packages for other frameworks in a matter of hours.

Since in Preact signals in `effect` are automatically tracked (unlike e.g. `useTask$` in Qwik), I need a way to prevent tracking. `.peek()` does not help me here, because our internal format does not allow to access framework specific properties of a signal. Also it is much more practicable to disable tracking for all signals at once.

Is it possible to implement an `untrack` function that disables tracking for all contained signals, basically like in [SolidJS](https://www.solidjs.com/docs/latest/api#untrack):

```js
const foo = signal('');
const bar = signal('');
const baz = signal('');

effect(() => {
  untrack(() => {
    foo.value;
    bar.value;
  });
  baz.value;
});
```

This would allow me to easily disable tracking in functions that are not supposed to be reactive but access various signals internally:

```js
function insert(form, name, options) {
  untrack(() => {
    // Code here
  });
}
```

Modular Forms has already received a lot of support in the SolidJS and Qwik communities, and I'm sure the library can be an asset to Preact as well.

**Comment by rschristian** [comment]
This came up a few times on Twitter (don't have links on hand, but should be easy enough to find w/ search if you really wanted to), but I think in general there was little interest. `.peek()` is the blessed way to prevent tracking, at least for now.

We can keep this open though.

**Comment by fabian-hiller** [comment]
I read through a tweet about this. It described why `untrack` is not needed in Preact, but not why it would be a bad idea, for example. As I understand it, Preact loses nothing when `untrack` is added. `.peek()` can still be described in the docs as the preferred approach. `untrack` can be optionally imported, which will only increase the size of the package if `untrack` is really needed. Or are there perhaps important reasons, which I am not aware of, not to implement `untrack` after all?

**Comment by rschristian** [comment]
> Preact loses nothing when `untrack` is added.

Bundle size is always a concern, as is simplicity of the API.

> which will only increase the size of the package if `untrack` is really needed

I think it's pretty unlikely an `untrack` implementation would be entirely pure.

**Comment by fabian-hiller** [comment]
Ok, I understand.
