### ISSUE TITLE
`useSignalEffect` does not update when a signal reference changes

### ISSUE THREAD

**Issue by fabian-hiller** [preactjs/signals#361]
There is a strange, but currently probably expected behavior when the reference of a signal passed as a prop changes. Here is a simple scenario:

- A signal is passed to a component via props. In the component the signal is used in `useSignalEffect`.
- Now the signal is replaced by another one. Since the reference changes, the component is re-rendered.
- Since `useSignalEffect` has no dependency array, the signal is not updated, causing bugs.

A simplified real-world example: [Preact RPEL](https://preactjs.com/repl?code=aW1wb3J0IHugcmVuZGVyIH0gZnJvbSAicHJlYWN0IjsKaW1wb3J0IHugc2lnbmFsLCBjb21wdXRlZCwgdXNlU2lnbmFsLCB1c2VTaWduYWxFZmZlY3QgfSBmcm9tICJAcHJlYWN0L3NpZ25hbHMiOwoKY29uc3QgaXRlbTAgPSBzaWduYWwoJ0EnKTsKY29uc3QgaXRlbTEgPSBzaWduYWwoJ0InKTsKY29uc3QgaXRlbXMgPSBbaXRlbTAsIGl0ZW0xXTsKCmNvbnN0IG9yZGVyID0gc2lnbmFsKFswLCAxXSk7Cgpjb25zdCBzd2FwRmlyc3RUd28gPSAoKSA9PiB7Cgljb25zdCBuZXh0T3JkZXIgPSBbLi4ub3JkZXIudmFsdWVdOwoJbmV4dE9yZGVyWzBdID0gb3JkZXIudmFsdWVbMV07CgluZXh0T3JkZXJbMV0gPSBvcmRlci52YWx1ZVswXTsKCW9yZGVyLnZhbHVlID0gbmV4dE9yZGVyOwp9OwoKZnVuY3Rpb24gSXRlbShwcm9wcykgewoJY29uc3QgdmFsdWUgPSB1c2VTaWduYWwoJycpOwogIHVzZVNpZ25hbEVmZmVjdCgoKSA9PiAodmFsdWUudmFsdWUgPSBwcm9wcy52YWx1ZS52YWx1ZSkpOwoJcmV0dXJuIDxzcGFuPnt2YWx1ZX08L3NwYW4%2BCn0KCmZ1bmN0aW9uIEFwcCgpIHsKICByZXR1cm4gKAogICAgPGRpdj4KCQkJPGRpdiBzdHlsZT0iZGlzcGxheTpmbGV4Ij4KCQkJCTxvbD4KCQkJCQl7b3JkZXIudmFsdWUubWFwKChwb3NpdGlvbiwgaW5kZXgpID0%2BICgKCQkJCQkJPGxpIGtleT17cG9zaXRpb259PgoJCQkJCQkJPEl0ZW0gdmFsdWU9e2l0ZW1zW2luZGV4XX0gLz4KCQkJCQkJPC9saT4KCQkJCQkpKX0KCQkJCTwvb2w%2BCgkJCQk8b2w%2BCgkJCQkJe29yZGVyLnZhbHVlLm1hcCgocG9zaXRpb24sIGluZGV4KSA9PiAoCgkJCQkJCTxsaSBrZXk9e3Bvc2l0aW9ufT4KCQkJCQkJCXtpdGVtc1tpbmRleF19CgkJCQkJCTwvbGk%2BCgkJCQkJKSl9CgkJCQk8L29sPgogICAgCTwvZGl2PgoJCQk8YnV0dG9uIG9uQ2xpY2s9e3N3YXBGaXJzdFR3b30%2BU3dhcCBmaXJzdCB0d288L2J1dHRvbj4KICAgIDwvZGl2PgogICk7Cn0KCnJlbmRlcig8QXBwIC8%2BLCBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgiYXBwIikpOwo%3D)

- Changing the order should have no influence on the order of the letters.
- The signal `item0` is always located at index `0` in the list.
- However, by `key={position}` the wrong signal moves in `useSignalEffect` to another index.
- This leads to a bug when displaying the list.

I noticed the problem when implementing [Modular Forms](https://modularforms.dev/) for Preact. In order to have the ability to set a listener to the value at a specific index in a list, the signal must not change in SolidJS. Therefore, I swap the values instead of moving the signals in the list.

**Comment by developit** [comment]
The way to do this is to store the prop signal in a local signal - signals track value changes over time, not signal changes over time, so if you need to react to a signal reference being changed over time you need to store it in another signal.

I typically use a helper called `useLiveSignal()` for this, which creates a Signal whose value is updated on every render if the provided argument is different than the signal's current value.

```
/**
 * useSignal(), but rerendering with a different value arg updates the signal.
 * Useful for: const a = useLiveSignal(props.a)
 */
export function useLiveSignal<T = any>(value: T): Signal<T> {
  const s = useSignal(value);
  if (s.peek() !== value) s.value = value;
  return s;
}
```

Using that helper, here's how you'd write the code to make effects work the way you're wanting them to:

```js
function Item(props) {
  // create a signal to hold the changing value of `props.value`: (which is itself a signal)
  const propValue = useLiveSignal(props.value);
  const value = useSignal('');
  useSignalEffect(() => (value.value = propValue.value.value));
  return <span>{value}</span>;
}
```

**Comment by fabian-hiller** [comment]
Thank you very much for your precise answer. I am now using a slightly modified version of `useLiveSignal` internally in Modular Forms, which ensures that the signals of a field within a list remain the same.

**Comment by jaskp** [comment]
> export function useLiveSignal<T = any>(value: T): Signal<T> {
>   const s = useSignal(value);
>   if (s.peek() !== value) s.value = value;
>   return s;
> }
> ```

Is it okay to mutate it in the render function? In React, you can only call `setState` in the render function if it belongs to the same component, but changing the signal could trigger other component re-renders, right? Is it fine in Preact?

**Comment by JoviDeCroock** [comment]
As most things, blank statements have to be taken with a gran of salt ;) but yes you can do so in Preact

**Comment by XantreGodlike** [comment]
I think `useLiveSignal` should be used on sender side, because of its easier to control on user side, if he passes signals conditionally

**Comment by XantreGodlike** [comment]
Wrapping all props in `useLiveSignal`, mostly when some props can be optional can be tricky

**Comment by leqwasd** [comment]
Well, in react - this is one of the reasons you have dependencies.
If you have component like this:
```tsx
const Component: React.FC = () => {
    const ref = React.useRef<HTMLDivElement>(null);
    React.useEffect(() => {
        console.log(ref.current);
    }, []); // No need ref here since the lifetime of the ref is equal to the useEffect
    return (
        <div ref={ref}>
            <ComponentWithWrapperRef parentRef={ref} />
        </div>
    );
};

const ComponentWithWrapperRef: React.FC<{ parentRef: React.RefObject<HTMLDivElement> }> = ({
    parentRef
}) => {
    React.useEffect(() => {
        console.log(parentRef.current);
    }, [parentRef]); // Here you need parentRef as a dependency because both - useRef and useEffect will be alive for the same time
    return <div />;
};

}
```

In my opinion, here - a dependency would be reasonable. Otherwise - how would you handle - if you would pass that signal down even further? Would you pass argument signal, and it would have to be wrapper there again in `useLiveSignal` ? Would you pass "liveSignal" - and then wrap it again in `useLiveSignal`? Then access it through `.value.value.value.value.value`?

**Comment by XantreGodlike** [comment]
I think [`useLinkedSignal`](https://github.com/XantreGodlike/preact-signals/blob/c2adf4abc5255f7270377cdb92d3614984f050ba/packages/utils/src/hooks/useLinkedSignal.ts#L36-L45) is great for this type of cases
