### ISSUE TITLE
Todolist REPL example is not worling for me 

### ISSUE THREAD

**Issue by atothek1** [preactjs/signals#365]
Dear preactjs Team,

as i wanted to play a bit around with the Signal API i have faced an issue that the Signalexample in the REPL is not properly working.

* adding new todos not rerendering the list
* checkmark a todo not rerendering the list and the completedCount
* removing a todo not rerendering the list.

I have logged in the handlers and the values are chaning but are not triggering the rerendering.

Do I miss something? shall the example work out of the box?

 Chrome 112.0.5615.138 on Windows 11

**Comment by rschristian** [comment]
The REPL on our site? We broke it at one point, don't think anyone's had the time to fix it yet.

See https://github.com/preactjs/preact-www/issues/978

**Comment by rschristian** [comment]
Going to close this out. Track that issue or let me know if you're referring to something else.
