### ISSUE TITLE
useSignalEffect not activated, effect triggers fine

### ISSUE THREAD

**Issue by isolin** [preactjs/signals#369]
- [x] Check if updating to the latest Preact version resolves the issue

This is probably some issue on my side, but I would be very glad if anyone could help me fixing it.

**To Reproduce**

I have a global state 
```ts
const state = {
  data: signal([0])
}

export default state;
```

When I reassign the data `state.data.value = [0, 1, 2]` the event is propagated only partially. If I have a functional component,  `effect` works.

```ts
export default function SceneTable() {
    let l = 0;
    effect(() => console.log(appstate.data.value.length));
    return <p>{appstate.data.value.length}+</p>;
}
```

But when I use a class `Component` instead, then `useSignalEffect` never triggers. Why so? Did I forget about something?

```ts
//a props interface IProps

export default class SceneTable extends Component<IProps> {
  useSignalEffect(){
    console.log(appstate.data.value.length);
    //never hits here
  }

  //some other methods
}
```

Maybe an important info: the class component is created as `tableRef = createRef<SceneTable>()` in a parent class component, while the my test with the functional component was stand-alone.

**Comment by rschristian** [comment]
Are you using React or Preact?

You should be using the hook versions (`useX`) in function components, and the non-hooks in class components. React limits hooks to function components, you cannot use them in class components. Preact does allow you to use hooks in class components, but it's quite unidiomatic and I'm not sure if support is guaranteed long-term.

**Comment by isolin** [comment]
Ah that was not clear to me. I thought it is a lifecycle method! I wrongly interpreted the following docs line

> When responding to signal changes within a component, use the hook variant: `useSignalEffect(fn)`.

as being a lifecycle method in class components.

So just out of curiosity - is there any concept that I could use within a class component to handle updates in signal values?

**Comment by isolin** [comment]
I rather thought of something like:

```ts
const data = signal([1,2,3]);

class CheckBox extends Component {
    process = effect(() => {
      //some heavy processing specific for this component
      this,state.data = this.process(data.value);
    });
}
```

I need to process data before rendering them and a computed signal makes not much sense as

1. the data view is specific for the component instance
2. it does not explicitly appear in the `render()` function but instead it is fed as scene data to a THREE.js scene

but that is my specific use case. The above concept with `process = effect(() => { /*...-* })` seems to work in class components and I anyway switched to functional in the meanwhile :)
