### ISSUE TITLE
It is possible to use @preact/signals-react with multiple webpack entries?

### ISSUE THREAD

**Issue by Alejandroid17** [preactjs/signals#379]
Hi, I'm working on a project where we have different React components that are injected into the page individually (multiple webpack entries) and I want to communicate the state between different components (on different entries) but using "signals" the state is not updated.

Some small code fragments:

```js
// webpack-configuration.js
module.export = {
    ...
    entry: {
        'componentA': 'path/component-a-dom.js',
        'componentB': 'path/component-b-dom.js',
    },
    ...
}
```

```js
// signal.js
import { signal } from "@preact/signals-react";

const count = signal(0);

export default count;
```

```js
// componentA.js
import count from "path/signal.js";

const componentA = () => {
    return <button onClick={() => count.value++}>My button ({count.value})</button>
}
```

```js
// componentB.js
import count from "path/signal.js";

const componentB = () => {
    return <div> The number is: {count.value}</div>
}

```

- In the componentA the value changes and the new value is shown. ✅
- In the componentB the value shown is the default value and never changes. ❌

Is it possible to work with this configuration/code?

Thank you very much!

**Comment by rschristian** [comment]
Using the Context API would likely be the simplest solution, therefore avoiding wrangling Webpack.

**Comment by Alejandroid17** [comment]
> Using the Context API (instead of direct import) would likely be the simplest solution, therefore avoiding wrangling Webpack.

@rschristian How would this be done? I can't get it to work.

```js
// webpack-configuration.js
module.export = {
    ...
    entry: {
        'componentA': 'path/componentA.js',
        'componentB': 'path/componentB.js',
    },
    ...
}
```

```js
// my-context.js

import { createContext } from 'react';
import { signal } from '@preact/signals-react';

const countSignal = signal(0);

const CountSignalContext = createContext(countSignal);

export default CountSignalContext;
```

```js
// componentA.js
import React, { useContext, useEffect, useState } from 'react';
import CountSignalContext from '../../../../my-context';

const componentA = () => {
    const countSignal = useContext(CountSignalContext);
    return <div>{countSignal}</div>;
}
```

```js
// componentB.js
import React, { useContext, useEffect, useState } from 'react';
import CountSignalContext from '../../../../my-context';

const componentB = () => {
    const countSignal = useContext(CountSignalContext);
    return <button onClick={() => countSignal.value++}>Signal: {countSignal.value}</button>;
}

```

The values are out of synch (7 - 0)

![image](https://github.com/preactjs/signals/assets/17381133/dc5fe41f-e4c1-449e-a300-a0310434c689)

**Comment by rschristian** [comment]
Have you forgotten to insert the provider higher up in the tree?

**Comment by Alejandroid17** [comment]
> 



> Have you forgotten to insert the provider higher up in the tree?
> 
> For example:
> 
> ```js
> import CountSignalContext from '../../../../my-context';
> const mySignal = signal(0);
> 
> const App = () => (
>   <CountSignalContext.Provider value={mySignal}>
>     <ComponentA />
>     <ComponentB />
>   </CountSignalContext.Provider>
> )
> ```

@rschristian I'm sorry, maybe I didn't explain myself well from the beginning. 

I have multiple webpack entries that are injected individually, so I don't see a way to add the "provider".

Code for injecting components into the DOM.

```js
// component-a-dom.js
const elementID = 'component-a';
const container = document.getElementById(elementID);

const root = createRoot(container);

root.render(
    <ComponentA>
);
```

```js
// component-b-dom.js
const elementID = 'component-b';
const container = document.getElementById(elementID);

const root = createRoot(container);

root.render(
    <ComponentB>
);
```
Thank you very much for your time.

**Comment by rschristian** [comment]
Going to close this out, it's probably better suited for Webpack's issues than here.
