### ISSUE TITLE
Devtools for debug

### ISSUE THREAD

**Issue by timsofteng** [preactjs/signals#384]
Hello. It would be cool to have some tool for debugging signals.

**Comment by rschristian** [comment]
The Preact devtools do support signals I believe.

**Comment by timsofteng** [comment]
> The [Preact devtools](https://github.com/preactjs/preact-devtools) browser extension does support signals I believe.

Does it work with react?

**Comment by rschristian** [comment]
It will not, no.

Someone could fork React's devtools, add in support for signals, and rerelease, but that'd be a lot of work and maintenance so it's probably unlikely to happen. Maybe someone in the community is interested in that though, not sure.

**Comment by rschristian** [comment]
Closing this out, this would need to be handled upstream. I don't think we'll be making dedicated devtools for signals.

**Comment by y0n3r** [comment]
@timsofteng Have you found anything for Signals dev tools support when used with React? I've been combing the internet and haven't really found anything. But, I noticed that if you create your initial app state with Signals and pass it down to your app using Context, you can highlight the provider in React Dev Tools and then click on the **Log this component data to the console** icon and get all of the corresponding values inside of the console. It's obviously not ideal and not as dynamic as just inspecting via dev tools, but it's way better than nothing. I hope this helps and I'll be continuing my search elsewhere...
