### ISSUE TITLE
re-render problems with React 'signal' 

### ISSUE THREAD

**Issue by fsterling1** [preactjs/signals#433]
I have a problem with very basic React project in respect to rendering page by using 'signal'.   
This is the project which is perfectly working in StackBlitz, but doesn't when I run It via visual studio code via 'npm start' in terminal
It's not working in the way that it doesn't update the value once the button is pressed.

https://stackblitz.com/edit/stackblitz-starters-cmfkij?file=package.json - it's working here.

all necessary packages installed.

What could be the reason?

**Comment by fsterling1** [comment]
@rschristian maybe you could have a look one more time. Sorry for disturbance. It runs perfectly in StackBlitz, but doesn't behave as expected locally. What could be the reason?

**Comment by rschristian** [comment]
Can't help much without a reproduction, sorry. Nothing really comes to mind.

If you can provide a reproduction of this issue we can reopen, else, it could be any manner of things specific to your system.
