### ISSUE TITLE
`@preact/signals-react-transform` unresolved `@trackSignals `

### ISSUE THREAD

**Issue by XantreGodlike** [preactjs/signals#438]
If we are using `@trackSignals` directive - component can be untransformed without aware.
Incorrect:
![image](https://github.com/preactjs/signals/assets/57757211/84d4580c-5625-44a8-bdec-bfbf061b8301)
Correct:
![image](https://github.com/preactjs/signals/assets/57757211/fbbece15-2bf7-4927-ae9e-22f3aade2cca)

I think this behaviour will be confusing for transform users, transform should throw error, at least, if cannot handle `@trackSignals`.

### Proposal:
Probably transform can also adapt more common directives pattern: `use client`, [`show source`](https://github.com/facebook/hermes/issues/612), [`worklet`](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/glossary#worklet).
Maybe something like `use signals`.
```tsx
const Counter = () => {
  'use signals';
  
  return <p>{sig.value}</p>
}
```

This syntax can be less confusing in terms of components wrapped in hocs

**Comment by XantreGodlike** [comment]
Also I have issue that rollup + esbuild clears this comments while bundling. This can be footgun for library authors

**Comment by andrewiggins** [comment]
I believe PR #441 fixes the issue mentioned at the top. Functions wrapped in higher-order functions are supported. For example:

```js
/** @trackSignals */
const C = memo(() => <div>{signal.value}</div>);
```

If you have an issue/concern with using rollup, etc. let's open a separate issue to discuss that.
