### ISSUE TITLE
source code issue

### ISSUE THREAD

**Issue by wiltchamberian** [preactjs/signals#449]
I am not sure, but it looks like a source code issue.
In  "packages/core/src/index.ts"  line 197 : evalContext._sources!._nextSource = node;
is the "!" a correct grammar?

**Comment by rschristian** [comment]
That's a non-null assertion operator in TypeScript: [Docs](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#non-null-assertion-operator)
