### ISSUE TITLE
signals-react: Wrong import path in dist/signals.d.ts causing TypeScript errors

### ISSUE THREAD

**Issue by fabianmichaelATform4** [preactjs/signals#450]
Hi,

we've discoverd an issue in dist/signals.d.ts that is causing TypeScript errors when building our app. It contains the following line:

```typescript
import { useSignal, useComputed, useSignalEffect } from "../runtime/src/index";
```

That causes the source file `../runtime/src/index` to be included by the TypeScript compiler when building our app causing the TypeScript errors. If I manually change the import path from `src` to `dist` it works fine

**Comment by XantreGodlike** [comment]
Probably it should be just `../runtime`

**Comment by rschristian** [comment]
> is causing TypeScript errors 

And what errors are those?

**Comment by paul-sachs** [comment]
I've also seen similar problems upgrading to most recent version. There errors I've seen are:

```
error TS7016: Could not find a declaration file for module 'use-sync-external-store/shim/index.js'. 'node_modules/.pnpm/use-sync-external-store@1.2.0_react@18.2.0/node_modules/use-sync-external-store/shim/index.js' implicitly has an 'any' type.
```

This causes problems since `@types/use-sync-external-store` is not a regular dependency and only a devDependency, it's not included by default.

**Comment by rschristian** [comment]
Enable `skipLibCheck`.

We shouldn't be adding `@types/use-sync-external-store` as a dep as it's not exposed to the user in any way, AFAIK.

**Comment by paul-sachs** [comment]
I have `skipLibCheck` set to true and it doesn't change anything.

**Comment by paul-sachs** [comment]
It doesn't:

> Skip type checking all .d.ts files.

And since this isn't a .d.ts file, it goes boom.

**Comment by rschristian** [comment]
That sounds like a TS bug. Errors, even in `.ts` files, should not be returned to the user if `skipLibCheck` is set and the module is imported by a `.d.ts` file.

**Comment by paul-sachs** [comment]
For reference, https://github.com/microsoft/TypeScript/issues/41883 discusses this in detail. I agree, `skipLibCheck` was the first thing i verified looking at this bug.

**Comment by paul-sachs** [comment]
As it turns out @XantreGodlike was correct, if we just don't import the full filepath, the local `package.json` resolves properly.

**Comment by XantreGodlike** [comment]
@rschristian Dependency will be bundled if useing `../runtime` or it will try to import it from runtime? If it will be bundled there should be no difference in behaviour

**Comment by rschristian** [comment]
> Dependency will be bundled if useing ../runtime or it will try to import it from runtime?

Microbundle doesn't bundle types, no.

**Comment by XantreGodlike** [comment]
I am not about types. I am about this import, which moves to d.ts after type emission.
https://github.com/preactjs/signals/blob/70ef4bb8694657ee43bcf2cf3f10732941c77f0b/packages/react/src/index.ts#L16

**Comment by rschristian** [comment]
https://www.npmjs.com/package/@preact/signals-react?activeTab=code

**Comment by XantreGodlike** [comment]
I know that now the source code of subpackage bundled. Will it be bundled if you replace the import from `../runtime/src/index` to just `../runtime`.
I think there will not be any difference in behaviour in that case - but types will be correct

**Comment by rschristian** [comment]
I'm not quite sure what you're referring to, but in any case, best way to get an answer is to clone & try out whatever you're after. I may have done a fair bit with Microbundle but my memory of its behavior isn't perfect.

**Comment by paul-sachs** [comment]
@XantreGodlike I can confirm that using `@preact/signals-react/runtime` works for my build. I wonder if it would make sense to make sure we don't ship `.ts` files to npm would guarantee these errors would be caught earlier. But the PR works, so that's good enough for me.

**Comment by rschristian** [comment]
> I wonder if it would make sense to make sure we don't ship .ts files to npm 

TS makes this a bit sketchy, but we (in the Preact org) generally prefer to ship the source files alongside built.
