### ISSUE TITLE
 React has detected a change in the order of hooks

### ISSUE THREAD

**Issue by sahajjain1** [preactjs/signals#452]
getting error : React has detected a change in the order of hooks... while using @preact/signals-react@1.1.1 and cant update the signal version above 1.1.1 as it will not work with my React version 17.0.2
any suggestions?

![image](https://github.com/preactjs/signals/assets/71086356/5aed67c4-23fb-4233-b908-7c3d90cccb89)

similar to https://github.com/preactjs/signals/issues/414

**Comment by XantreGodlike** [comment]
Do you using signals with Vite? Webpack?
Which version of `@preact/signals-react` is not working with 17.0.2? I know that `1.2.1` should work

**Comment by sahajjain1** [comment]
Using Webpack
i tired with 1.2.1 and 1.1.1 getting the same above issue React has detected a change in the order of hooks. but when i tried your (https://github.com/XantreGodlike/preact-signals/tree/main/packages/react) it was working perfectly.
we have decided to upgrade the react to latest versrion and now we can use the latest version of @preact/signals-react hopefully the issue wont show up again

**Comment by edgars-sirokovs** [comment]
I encountered this warning with Remix (v2.3.1) + Vite (v5.0.4), @preact/signals-react v1.3.7

```Warning: React has detected a change in the order of Hooks called by RemixBrowser.```
