### ISSUE TITLE
No component rerendering with @preact/signal-react

### ISSUE THREAD

**Issue by roo7690** [preactjs/signals#453]
Hello, I'm having a problem with @preact/signal-react.
Using this code provided by the documentation,
```js
import { useSignal, useComputed, effect } from "@preact/signals-react";

export default function () {
	const count = useSignal(0);
	const double = useComputed(() => count.value * 2);

	effect(()=>{
		console.log(count.value,double.value)
	})

	return (
		<button onClick={() => count.value++}>
			Value: {count.value}, value x 2 = {double.value}
		</button>
	);
}
```
there is a subscription of the console.log() that re-executes with each change but no rerendering of the component

**Comment by XantreGodlike** [comment]
In which envirement do you using signals? Webpack? Vite? Next.js?

**Comment by jesseagleboy** [comment]
Just as speculation from my time working with Preact Signals, the issue could be because the `count.value` and `double.value` in your JSX are not being used in the proper way. Any signal or computed value within the JSX should be inserted without explicitly saying `.value`. Preact Signals handles the rendering behind the scenes. But as @XantreGodlike asked above, I've noticed Vite and Webpack can have different results at times.

**Comment by rschristian** [comment]
> Any signal or computed value within the JSX should be inserted without explicitly saying `.value`.

Not quite, no. Using `.value` just opts you out of the direct text node binding, you absolutely can do it though. Just need a full rerender of the component to update.

**Comment by XantreGodlike** [comment]
> Just as speculation from my time working with Preact Signals, the issue could be because the `count.value` and `double.value` in your JSX are not being used in the proper way. Any signal or computed value within the JSX should be inserted without explicitly saying `.value`. Preact Signals handles the rendering behind the scenes. But as @XantreGodlike asked above, I've noticed Vite and Webpack can have different results at times.

Omitting `.value` is fully optional performance optimization. It should work any way

**Comment by roo7690** [comment]
@XantreGodlike 
Oops, I should have mentioned. It's on Nextjs; through this increment, we can see that there is an omission.
```js
"use client"
import { effect, signal } from "@preact/signals-react";

const i=signal(0)
setInterval(()=>i.value++,1000)

effect(()=>{
	console.log(i.value)
})

export default function Page () {

	return i
}
```

**Comment by XantreGodlike** [comment]
@roo7690 use can try my [`@preact-signals/safe-react`](https://github.com/XantreGodlike/preact-signals/tree/main/packages/react) with manual subscribing components to signals via HOC. It's not so cool as automatic tracking, but for now I don't know better options for next.js. For now I researching opportunity to migrate babel plugin to swc to make it working with next.js https://github.com/XantreGodlike/preact-signals/issues/43

**Comment by XantreGodlike** [comment]
Did you run `yarn start --reset-cache`?

**Comment by XantreGodlike** [comment]
Did you changed babel config?

**Comment by Dylan-yoon-mp** [comment]
yes I did

**Comment by kerituni12** [comment]
same issue with "vite": "^4.5.0" and "@preact/signals-react": "^2.0.0"

**Comment by Loque18** [comment]
same issue

**Comment by sellwawy** [comment]
Same issue in Next.js and Vite.

**Comment by XantreGodlike** [comment]
@rschristian Should we add Troubleshooting section to readme? I can provide PR

**Comment by rschristian** [comment]
What would that entail (especially in relation to this issue)?

**Comment by XantreGodlike** [comment]
> What would that entail (especially in relation to this issue)?

Components don't track signals
or
Components do not update if signal value changes
or
Lack of component reactivity

**Comment by ReevMich** [comment]
For me, the simple vite react typescript template doesnt work with @preact/signal-react 2.0.0, when I switch to 1.3.8 it works as id expect. I have also tried the same thing in a create react app webpack environment. The switch to version 1.38 does resolve the issue. 
https://stackblitz.com/edit/vitejs-vite-pj3xda?file=package.json,src%2FApp.tsx&terminal=dev

**Comment by rschristian** [comment]
> For me, the simple vite react typescript template doesnt work with @preact/signal-react 2.0.0 using the .value

You haven't followed the [v2 usage instructions](https://github.com/preactjs/signals/tree/main/packages/react#react-integration)

**Comment by ReevMich** [comment]
> > For me, the simple vite react typescript template doesnt work with @preact/signal-react 2.0.0 using the .value
> 
> You haven't followed the [v2 usage instructions](https://github.com/preactjs/signals/tree/main/packages/react#react-integration)

Your right, I missed the babel stuff. Thanks.

**Comment by PivaRos** [comment]
**Quick solution:**

This is probably because you didn't set the babel config.

Solution 1:
Setting the babel config should fix the issue 

Solution 2: 
Adding the hook useSignals() in the top of the file

**Comment by rschristian** [comment]
Closing as answered.
