### ISSUE TITLE
Update Array without re-render non-updated items

### ISSUE THREAD

**Issue by Jeremy38100** [preactjs/signals#464]
Hello,

Here an example of simple code of an array in a signal. Is there a way to re-render only updated/new items in the array for performance optimisation.

```js
import { render } from "preact";
import { signal } from "@preact/signals";

const arr = signal([{value: 1}]);

function Item({item}) {
	// This is logged for every items on Add
	console.log('render', item.value)
	return (<li>{item.value}</li>)
}
 
function TodoList() {
  const addItem = () => arr.value = [...arr.value, {value: Math.random()}]
  return (
    <>
      <button onClick={addItem}>Add</button>
      <ul>
        {arr.value.map(item => (<Item item={item} />))}
      </ul>
    </>
  );
}

render(<TodoList />, document.getElementById("app"));
````

[REPL Playground](https://preactjs.com/repl?code=aW1wb3J0IHugcmVuZGVyIH0gZnJvbSAicHJlYWN0IjsKaW1wb3J0IHugc2lnbmFsLCBjb21wdXRlZCB9IGZyb20gIkBwcmVhY3Qvc2lnbmFscyI7Cgpjb25zdCBhcnIgPSBzaWduYWwoW3t2YWx1ZTogMX1dKTsKCmZ1bmN0aW9uIEl0ZW0oe2l0ZW19KSB7Cgljb25zb2xlLmxvZygncmVuZGVyJywgaXRlbS52YWx1ZSkKCXJldHVybiAoPGxpPntpdGVtLnZhbHVlfTwvbGk%2BKQp9CiAKZnVuY3Rpb24gVG9kb0xpc3QoKSB7CgoJY29uc3QgYWRkSXRlbSA9ICgpID0%2BIGFyci52YWx1ZSA9IFsuLi5hcnIudmFsdWUsIHt2YWx1ZTogTWF0aC5yYW5kb20oKX1dCgogIHJldHVybiAoCiAgICA8PgogICAgICA8YnV0dG9uIG9uQ2xpY2s9e2FkZEl0ZW19PkFkZDwvYnV0dG9uPgogICAgICA8dWw%2BCiAgICAgICAge2Fyci52YWx1ZS5tYXAoaXRlbSA9PiAoPEl0ZW0gaXRlbT17aXRlbX0gLz4pKX0KICAgICAgPC91bD4KICAgIDwvPgogICk7Cn0KCnJlbmRlcig8VG9kb0xpc3QgLz4sIGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCJhcHAiKSk7Cgo%3D)

Thank you for your help,

Awesome work on this library ❤️

**Comment by rschristian** [comment]
Can you get away with an array of components, instead of an array of data?

```jsx
import { render } from "preact";
import { signal } from "@preact/signals";

const arr = signal([<Item item={1} />]);

function Item({ item }) {
  console.log("render", item);
  return <li>{item}</li>;
}

function TodoList() {
  const addItem = () => (arr.value = [...arr.value, <Item item={Math.random()} />]);

  return (
    <>
      <button onClick={addItem}>Add</button>
      <ul>{arr.value}</ul>
    </>
  );
}

render(<TodoList />, document.getElementById("app"));

```

**Comment by Jeremy38100** [comment]
Interesting!
But I'm facing a case where I can not get away with an array of components instead of an array of data. I really need the array of data.

**Comment by rschristian** [comment]
Unfortunately I believe that's your only option.

**Comment by Jeremy38100** [comment]
OK, thank you for your response and proposition !
