### ISSUE TITLE
@preact/signals-react not updating dom while using "variable.value" but does when using "variable"

### ISSUE THREAD

**Issue by KillerMax4299** [preactjs/signals#469]
## This doesn't update the count value in the button 
![image](https://github.com/preactjs/signals/assets/92305008/301568a9-caf3-434d-9d88-e4f9e9f638f7)
## But this does
![image](https://github.com/preactjs/signals/assets/92305008/b5a730a0-b94c-46fa-9e3b-77818d2f405b)

 But both should work right. Later was just an optimization (optional)
 
I found this issue in `@preact/signals-react` **v2.0.0** but while in **v1.3.8** everything works fine. So for the time being I'm just using the older version.

**Comment by andrewiggins** [comment]
Hey @KillerMax4299 :wave: v2 is a new major release of signals-react and as such has some breaking changes. Check the [Changelog](https://github.com/preactjs/signals/blob/main/packages/react/CHANGELOG.md#major-changes) for details on the breaking change.

Have you added `import "@preact/signals-react/auto";` to the root of your application? That's the fastest way to get the same behavior as v1.3.8.

Just realizing I updated the Readme with the new instructions but didn't but a larger notice about the v2 changes. Lemme do that.

**Comment by hta218** [comment]
Hey @andrewiggins, added `` does work. Thanks for mentioning that.

The `v2.0.0` changelog says: "Check out the new Readme for the newly supported ways of using signals in React". But where is the new **ReadMe**? 
![image](https://github.com/preactjs/signals/assets/24975260/f5379593-e962-416c-a370-521af649ef36)

**Comment by XantreGodlike** [comment]
https://github.com/preactjs/signals/tree/main/packages/react

**Comment by hiddenLadder** [comment]
so how do i use it with vite or nextjs? there's no babel, should i add useSignals() hook to every component that uses signals?

**Comment by noopurphalak** [comment]
@XantreGodlike No `useSignals` hook is exported in the `@preact/signals-react` in version `2.0.0`

<img width="1103" alt="Screenshot 2023-12-27 at 5 00 13 PM" src="https://github.com/preactjs/signals/assets/8924488/fd0b8b90-356e-4291-9c8b-59a8db355b7b">

**Comment by XantreGodlike** [comment]
> @XantreGodlike No `useSignals` hook is exported in the `@preact/signals-react` in version `2.0.0`
> 
> <img width="1103" alt="Screenshot 2023-12-27 at 5 00 13 PM" src="https://github.com/preactjs/signals/assets/8924488/fd0b8b90-356e-4291-9c8b-59a8db355b7b">
> 

I've never been exported from the main entry

**Comment by noopurphalak** [comment]
> > @XantreGodlike No `useSignals` hook is exported in the `@preact/signals-react` in version `2.0.0`
> > <img alt="Screenshot 2023-12-27 at 5 00 13 PM" width="1103" src="https://private-user-images.githubusercontent.com/8924488/293023163-fd0b8b90-356e-4291-9c8b-59a8db355b7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NDY5NzgsIm5iZiI6MTcwMzc0NjY3OCwicGF0aCI6Ii84OTI0NDg4LzI5MzAyMzE2My1mZDBiOGI5MC0zNTZlLTQyOTEtOWM4Yi01OWE4ZGIzNTViN2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjhUMDY1NzU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWE0ODMwNmM4ZGVkMzViN2VhMTQ2NGE0M2JjYjIyMThjODhjMGUzODdmOGUzZWFhYjMzNTE2M2M4ODA2MjgyMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.z7PZzCz6gUR3aBwUj_xrFX2L9MGUGBgZaTkKLL01-X8">
> 
> I've never been exported from the main entry

Well, the documentation asks to import `useSignals` from `@preact/signals-react` and when I try to do that, it gives me an error. Refer the screenshot below:

<img width="715" alt="Screenshot 2023-12-28 at 12 29 14 PM" src="https://github.com/preactjs/signals/assets/8924488/fc531f26-ec8c-471f-97c9-492db9b6b2c1">

**Comment by XantreGodlike** [comment]
@JoviDeCroock @noopurphalak 
#472

**Comment by noopurphalak** [comment]
@XantreGodlike Okay, got it...

**Comment by besabellacyrus** [comment]
> Hey @KillerMax4299 👋 v2 is a new major release of signals-react and as such has some breaking changes. Check the [Changelog](https://github.com/preactjs/signals/blob/main/packages/react/CHANGELOG.md#major-changes) for details on the breaking change.
> 
> Have you added `import "@preact/signals-react/auto";` to the root of your application? That's the fastest way to get the same behavior as v1.3.8.
> 
> Just realizing I updated the Readme with the new instructions but didn't but a larger notice about the v2 changes. Lemme do that.

adding this one inside App.js works too. Thanks!
