### ISSUE TITLE
@preact/signals-react@2.0.0 not re-exporting useSignals

### ISSUE THREAD

**Issue by JonAbrams** [preactjs/signals#473]
According [to the docs](https://github.com/preactjs/signals/blob/d7f43ef5c9b6516cd93a12c3f647409cfd8c62be/packages/react/README.md#usesignals-hook), I should be able to `import { useSignals } from '@preact/signals-react'`, but since `useSignals` is not re-exported, I need to do this instead: `import { useSignals } from '@preact/signals-react/runtime'`.

**Comment by XantreGodlike** [comment]
I think it's better to just replace `@preact/signals-react` -> `@preact/signals-react/runtime` in README.md

**Comment by XantreGodlike** [comment]
#472 Like that

**Comment by JonAbrams** [comment]
Seems inconsistent to re-export `useSignal` but not `useSignals` from the same place.

**Comment by XantreGodlike** [comment]
What is the problem to import it from runtime. It's logically little bit different stuff

**Comment by JonAbrams** [comment]
Adds an extra import statement, for no reason. It’s just cleaner to have
all of a modules exports in one place.

**Comment by rschristian** [comment]
Cleanliness isn't so much relevant as intended default usage -- `useSignals` being exported from a subpath (`/runtime`) would indicate it's more of an "opt-in" than a default.

Not 100% sure what Andre had meant for though. @andrewiggins friendly ping if you're not too busy with holiday stuff

**Comment by dotte1** [comment]
Yes please fix the README for those of us too lazy to read the Issues 😆. I'm a brand new user of @preact-signals in a React project, so this was a bit of head scratcher at first wondering why things weren't working, uh, reactively...also, my project doesn't use Babel.

Anyway, keep up the good work and thanks for the clarifications, everyone 👍

**Comment by Merri** [comment]
> I think it's better to just replace `@preact/signals-react` -> `@preact/signals-react/runtime` in README.md

Just noting here that readme on npm site still shows outdated documentation.

**Comment by XantreGodlike** [comment]
> > I think it's better to just replace `@preact/signals-react` -> `@preact/signals-react/runtime` in README.md
> 
> Just noting here that readme on npm site still shows outdated documentation.

It will be updated with the next release. It is possible to release it with only changes in readme, too
