### ISSUE TITLE
No way to use it with Mobx

### ISSUE THREAD

**Issue by FishOrBear** [preactjs/signals#476]
Error: It is not allowed to use shouldComponentUpdate in observer based components.

```
import { signal } from "@preact/signals";
import { observer } from "mobx-react";
import { Component } from "preact";

signal(1);

@observer
export class App extends Component<{}, {}>{
    render()
    {
        return (
            <div>
                Hello World
            </div>
        );
    }
}

```

**Comment by rschristian** [comment]
Why would you use this with mobx? Generally they address the same problem and it'd make sense to use one or the other.

**Comment by FishOrBear** [comment]
Indeed, I am in the exploratory stage.
Because singnals does not support object Store, I want to try it out.
signals(0) is similar to mobx.observable.box(0)

**Comment by rschristian** [comment]
FWIW, I can't reproduce this: https://stackblitz.com/edit/vitejs-vite-rfbmef?file=src%2Fmain.jsx
