### ISSUE TITLE
Signals value do not trigger the component rerender if used in the return statement in JSX

### ISSUE THREAD

**Issue by GioOli7** [preactjs/signals#478]
Hello everyone, I'm new to Signals, and while running some tests, I'm noticing a rather strange issue.
I'm experiencing an issue with using Signal values within the return statement in JSX. I've noticed that if I directly use Signal values in the return statement, the component doesn't re-render, and thus, my UI doesn't react to changes in the state of variables initialized with Signals. To make my application work correctly, I have to extract the logic and components to be rendered into a variable outside the return statement and only reference the variable in the return statement.

I show some code as an example.

**_userData from useGoogleAuth() is Signals variable stored in a separate file_**

In this example my component do not react to the signals change
<img width="500" alt="image" src="https://github.com/preactjs/signals/assets/74468160/8d3ef51a-8700-4296-9f5c-dc0e2e96f141">

to make it work, i need to extract the logic outside like this:
<img width="500" alt="image" src="https://github.com/preactjs/signals/assets/74468160/7753a230-a83e-4d3b-a1a0-8b8247a09340">

I'm using @preact/signals-react and Vite

It's a bug or i'm doing it wrong?

Thanks in advance for any help.

**Comment by XantreGodlike** [comment]
Are you using the babel plugin? Send vite config please

**Comment by GioOli7** [comment]
No, this is my vite config

```
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
})
```

**Comment by rschristian** [comment]
Don't provide reproductions as screenshots please.

If you're not using the Babel plugin, then you need to be calling `useSignals()`. Please read the instructions:

https://github.com/preactjs/signals/tree/main/packages/react#react-integration

**Comment by GioOli7** [comment]
Thanks for help, I was using [this](https://preactjs.com/guide/v10/signals/) documentation
Now I using babel plugin and the component is react again. 
But i don't get it. Now, however, a change in the value of the Signals variable triggers me to render all sibling and child components as if I were using useState.

This is a code example. with the implementation shown in the second screenshot I could open and close the modal without triggering the rendering of the main component. Now instead both the main component and the Test component are re-rendered. In its current state, it is as if I were using useState

```

export const isExpenseModalOpen = signal(false);
import Test from '../generic/Test';

function Main() {
  console.log("main rerender")
  const {getAllData, updateData} = useFirebase()
  const [allData, setAllData] = useState({})

  useEffect(()=>{
        async function fetch(){
            setAllData(await getAllData())
        }
        // fetch()
  },[])

  // const addExpenseModal = computed(() => {
  //   if(isExpenseModalOpen.value === true){
  //     return (
  //       <Modal title="add" >
  //           <div>ciao</div>
  //       </Modal> 
  //     )
  //   }
  // });

  return (
    <div className='main'>
      <button className='addExpense' onClick={() => isExpenseModalOpen.value = !isExpenseModalOpen.value}>
        +
      </button>
      { 
        isExpenseModalOpen.value && (
          <Modal title="add" >
              <div>ciao</div>
          </Modal> 
        )
      }
      <Test />

    </div>
  )
}
```

This is the logs when open and close the modal
<img width="479" alt="image" src="https://github.com/preactjs/signals/assets/74468160/5c2b2172-2dfe-46e5-8797-4b4e7fa29141">

**Comment by rschristian** [comment]
> Thanks for help, I was using [this](https://preactjs.com/guide/v10/signals/) documentation

Being the Preact website, that's for Preact usage. Docs for the React integration are kept in this repo.

Someone's raised the idea of adding a banner to that page in the past to get React users back to the right place but I don't think anyone's worked on that yet.

> But i don't get it. Now, however, a change in the value of the Signals variable triggers me to render all sibling and child components as if I were using useState.

Hm, not sure. I'm not familiar with the React integration. Indeed, neither the Babel plugin & `useSignals` seem to support the rendering optimization at the moment.

**Comment by XantreGodlike** [comment]
@rschristian In place dom updates via signals have never worked with react integration. But it realizable with custom components

**Comment by rschristian** [comment]
> In place dom updates via signals have never worked with react integration

That doesn't sound right, and our docs indicate otherwise. Some usages did have issues depending on how they were themselves also using internals though (which is to be expected).

Wasn't skipping the VDOM of course but it should've been updating w/out rerenders.

**Comment by XantreGodlike** [comment]
It always worked like just signal value unpacking so parent component will rerender.
https://github.com/preactjs/signals/blob/e42199ed4f00cc751cdf0f0b9de44c818a28c044/packages/react/src/index.ts#L33

But putting signals as JSX have been working

**Comment by rschristian** [comment]
Oh apologies, I had misread their example.

Yup, if not binding to a text node, rerenders are unavoidable on signal value change. All we can do is ask the React team for improvements here (though they're completely disinterested, so don't count on it).

**Comment by GioOli7** [comment]
Thank you @rschristian and @XantreGodlike for the clarification

**Comment by ElBaDaNoS** [comment]
To clarify, are you suggesting that preact-signals are not functioning within React as anticipated?

**Comment by rschristian** [comment]
> To clarify, are you suggesting that preact-signals are not functioning within React as anticipated?

Not sure if you're asking OP or me (I struck through my previous comment, as I had misread the provided example), but no, this should be working as intended.
