### ISSUE TITLE
Question: Garbage Collection

### ISSUE THREAD

**Issue by HappyStriker** [preactjs/signals#483]
Hello,

I have a quick question about the garbage collection of signals, more specifically of the `computed` type. Lets look at the following code, which should use the signal `time` directly instead of `time.value` in the `render` method, but it is just a simplification for the demonstration:

```javascript
import { Component, html, signal, computed, render } from './preact.js';


class App extends Component {
  static {
    this.clock = signal(new Date());
    setInterval(() => this.clock.value = new Date(), 1_000);
  }

  render() {
    const time = computed(() => App.clock.value.toTimeString('de').slice(0, 8));
    return html`
      <h1>Hello World, it is ${time.value} o'clock.</h1>
    `;
  }
}


render(html`<${App}/>`, document.body);
```

The class method `render` gets called every second in order to do get the latest vdom of the component. But what happens to the previous `time` signals? Do they automatically get garbage collected or is it my job as developer to clean up those signals to prevent any memory leaks?

Thanks for the clarification!

**Comment by rschristian** [comment]
They should get GC'd just fine.

That being said, you'd avoid any extra GC work by using `useComputed` in the render function. As it is, `time` has to be recreated on every rerender.

**Comment by HappyStriker** [comment]
> They should get GC'd just fine.
> 
> That being said, you'd avoid any extra GC work by using `useComputed` in the render function. As it is, `time` has to be recreated on every rerender.

Thank you very much for the explanation.
