### ISSUE TITLE
Where are the release notes?

### ISSUE THREAD

**Issue by deavial** [preactjs/signals#488]
Where are the release notes currently being published to? I see a semver breaking change (2.0) in npm, but I can neither find release notes for it or even a git tag to diff.

**Comment by XantreGodlike** [comment]
https://github.com/preactjs/signals/blob/main/packages/react/CHANGELOG.md

**Comment by rschristian** [comment]
Looks like something went a bit wonky with changesets at some point, I believe it was supposed to do this automatically.

I'll see if I can't cut some time out to fix this later

**Comment by rschristian** [comment]
Got the time to back date all the releases, can find 2.0.0 here:

https://github.com/preactjs/signals/releases/tag/%40preact%2Fsignals-react%402.0.0
