### ISSUE TITLE
Do signal effects support clean up functions?

### ISSUE THREAD

**Issue by gabrielcoronel** [preactjs/signals#495]
What I mean by "clean up functions" is a signal analog to traditional React's `useEffect` clean up functions. For example, with `useEffect` one can set a clean up function for an update effect, this function will run right before the next update, "undoing" ("cleaning up") such effect:

```js
useEffect(() => {
  Chat.connect(username)

  // Clean up function
  return () => Chat.disconnect(username)
}, [username])
```

Do signal `effect`s (`useSignalEffect`) support this feature? If so, how? If not, what is signals' alternative for "cleaning up" effects?

I've read through the [documentation](https://preactjs.com/guide/v10/signals/) and I haven't find anything similar so far.

**Comment by XantreGodlike** [comment]
You can return function from effect and it will run when effect dependencies changed

**Comment by gabrielcoronel** [comment]
> You can return function from effect and it will run when effect dependencies changed

Ok, I didn't know that. Is that in any official documentation you could me point me to?

**Comment by XantreGodlike** [comment]
Seems to be there is no info in docs about it but, it's obvious from types

**Comment by XantreGodlike** [comment]
I think we should add info about it

**Comment by gabrielcoronel** [comment]
I submitted a pull request to the documentation repository including information about signals
