### ISSUE TITLE
@preact/signals-react@2.0.0 signals don't update with useEffect hooks.

### ISSUE THREAD

**Issue by mimiqkz** [preactjs/signals#497]
```
import {signal} from '@preact/signals-react'
const data = signal()
React.useEffect(() => {
  const fetchData = async () => {
    try {
      const newData = await someAPICall()
      data.value = newData
    } catch (e) {
      // Handle error here
    }
  } 
  fetchData()
}, [])
```

In the older version (v1.3.8), the signal data will be updated on `data.value = newData`. However, since updating to v2.00, this breaks. Don't see any significant changes on the documentation. What to do to fix this?

**Comment by XantreGodlike** [comment]
Please provide the exact code, because it's hard to figure out what needs to be updated and how signal used

**Comment by mimiqkz** [comment]
@XantreGodlike Hello, I'm confused but this is the code.
```
import React from 'react'
import {signal} from '@preact/signals-react'


const data = signal()

export default function CompA() {
  React.useEffect(() => {
    const fetchData = async () => {
      try {
        const newData = await someAPICall()
        data.value = newData // code reaches here btw
        console.log(newData) // new data actually printed out here no problem
      } catch (e) {
        // Handle error here
      }
    } 
    fetchData()
  }, [])

 // Return shows hi but not data.value because signal is not being updated
  return (
    <p>{data.value || 'hi'}<p/>
  )
}
```

**Comment by XantreGodlike** [comment]
@mimiqkz do you use the babel plugin? How is the file of the component named?
You can try to add `/** @useSignals **/` before function declaration statement

**Comment by mimiqkz** [comment]
@XantreGodlike `/** @useSignals **/ `doesn't work. I'm using nextjs 13.4.4, with no babel plugin. So signals in v.2.0.0 have 0 auto update?

**Comment by XantreGodlike** [comment]
@mimiqkz 
You have these options:
- use the `useSignals()` hook on top of each component that uses signals
- try to import `@preact/signals-react/auto` in the root of the application (probably will not work if you use app directory)
- use an swc plugin with [`@preact-signals/safe-react`](https://www.npmjs.com/package/@preact-signals/safe-react#nextjs-integration) which inserts `useSignals` to your component automatically

**Comment by mimiqkz** [comment]
@mimiqkz Hello, add `useSignals()` works for me 👍
