### ISSUE TITLE
@preact/signals-react value changing didn't call rerender components

### ISSUE THREAD

**Issue by CrazyRedTime** [preactjs/signals#500]
It's working fine on 1.3.6 version, but after update to version 2.0.0 expected behavior is broken. [Example](https://codesandbox.io/p/sandbox/signalsreport-2fgcfl?file=%2Fsrc%2FApp.js%3A15%2C25)

**Comment by betula** [comment]
It’s will work only with Preact, but for React you should use Babel plugin or function “useSignals()” for make a component reactive.

```typescript
import { useSignals } from "@preact/signals-react/runtime";

const count = signal(0);

function CounterValue() {
	useSignals();
	return <p>Value: {count.value}</p>;
}
```

**Comment by rschristian** [comment]
Please don't upgrade majors without reading the docs to see what's changed.

https://github.com/preactjs/signals/tree/main/packages/react#react-integration
