### ISSUE TITLE
Refererring signals in JSX in Next 14, AppDir, Client component

### ISSUE THREAD

**Issue by sanskar-19** [preactjs/signals#504]
Consider a scenario below : 

`<button onClick={() => count.value++}>
Value: {count}, value x 2 = {double}
</button>`

The above has been referred from the NPM documentation but, small difference is they referred signals as `count.value` and `double.value` in the JSX. It didn't seem to update the same in UI. 

Not until I referred the signals as `signal` instead of `signal.value` in the JSX.

<img width="657" alt="image" src="https://github.com/preactjs/signals/assets/63312055/662e3070-b32e-41d5-9e0b-7a7d2218edb6">

<img width="511" alt="image" src="https://github.com/preactjs/signals/assets/63312055/16937262-56da-4b29-b9b4-77e5f5c3646a">

The output above.

Repository Link : `https://github.com/sanskar-19/preact-signals`

_Originally posted by @sanskar-19 in https://github.com/preactjs/signals/issues/466#issuecomment-1913514903_

**Comment by rschristian** [comment]
You're not calling `useSignals()` or using the Babel plugin. Need to do one or the other.

**Comment by sanskar-19** [comment]
> You're not calling `useSignals()` or using the Babel plugin. Need to do one or the other.

So even when I am creating a signal using the `useSignal()` hook, still I have to manually call the `useSignals()`

**Comment by rschristian** [comment]
[As the instructions say](https://github.com/preactjs/signals/tree/main/packages/react#usesignals-hook), yes.

**Comment by sanskar-19** [comment]
> [As the instructions say](https://github.com/preactjs/signals/tree/main/packages/react#usesignals-hook), yes.

If you see the instructions it is mentioned that if you want to create signals inside of your component, simply calling useSignal() works. The `useSignals()` call is written when signal has been defined outside the component. Can you clarify this?

**Comment by rschristian** [comment]
> If you see the instructions it is mentioned that if you want to create signals inside of your component, simply calling useSignal() works. The useSignals() call is written when signal has been defined outside the component. Can you clarify this?

You're confusing two different things.

You must use either the Babel plugin or `useSignals()`. They're what sets up and facilitates the reactivity. Without them, you would not get rerenders upon signal changes.

For creating signals, use `signal()` if outside a component and `useSignal()` inside, to get a stable reference.

**Comment by sanskar-19** [comment]
> > If you see the instructions it is mentioned that if you want to create signals inside of your component, simply calling useSignal() works. The useSignals() call is written when signal has been defined outside the component. Can you clarify this?
> 
> You're confusing two different things.
> 
> You must use either the Babel plugin or `useSignals()`. They're what sets up and facilitates the reactivity. Without them, you would not get rerenders upon signal changes.
> 
> For creating signals, use `signal()` if outside a component and `useSignal()` inside, to get a stable reference.

Oh. I thought since the hook has been defined so it would be handling that internally. But that brings me to my next question on why did the `signal` worked and not `signal.value`

**Comment by sanskar-19** [comment]
> > If you see the instructions it is mentioned that if you want to create signals inside of your component, simply calling useSignal() works. The useSignals() call is written when signal has been defined outside the component. Can you clarify this?
> 
> You're confusing two different things.
> 
> You must use either the Babel plugin or `useSignals()`. They're what sets up and facilitates the reactivity. Without them, you would not get rerenders upon signal changes.
> 
> For creating signals, use `signal()` if outside a component and `useSignal()` inside, to get a stable reference.

And another point over this, that as you can see, I am referencing a NEXT.js project which has now moved to a SWC instead of babel compiler. So, the only option I see left is to call the `useSignals` hook, but don't you think that is a bit too much, to call this particular hook. 

And again why `signal` worked and not `signal.value`.

**Comment by rschristian** [comment]
> So, the only option I see left is to call the useSignals hook, but don't you think that is a bit too much, to call this particular hook inside every component where I am using signals.

React limits what we can do. We provide options as we can, but unfortunately, this is just the way it is for now.

Preact doesn't have this issue, nor do other UI libraries that want to integrate with signals.

> And again why signal worked and not signal.value.

You'd have to look into the source code yourself for that, I'm not familiar enough with the React implementation.

**Comment by sanskar-19** [comment]
So then what do you suggest as a standard way to consume signals in react?

Can you direct my request to the concerned member who is familiar with the react implementation. 

I agree that Preact is a good choice for faster implementations but the community for React has been there for long.
