### ISSUE TITLE
Array splice doesn't trigger re-render

### ISSUE THREAD

**Issue by chinmaypant21** [preactjs/signals#510]
There is no re-render trigger while updating an array stored in a signal using array splice. Here is an example of the issue:

```
const tasks = signal<any[]>(['Task1', 'Task2', 'Task3']);

const Screen = () => {
    function handleRemoveTask(idx: number){
    activeWindows.value.splice(idx,1)
    ))
  }
  return (
  <>...</>
  )
}
```

**Comment by XantreGodlike** [comment]
Signals can only rerender if you assign new value with `.value` property.
Splice is a mutating array in place. So you need to use: `s.value = s.value.toSpliced(...)`

**Comment by rschristian** [comment]
Yup. working as intended.
