### ISSUE TITLE
computed fn problem

### ISSUE THREAD

**Issue by Darka7** [preactjs/signals#514]
using a signal it does not detect the change in computed, it is only activated once when the value is changed it does not detect it again

 "@preact/signals-react": "2.0.0",

**Comment by XantreGodlike** [comment]
Can you provide any repro?

**Comment by Darka7** [comment]
Hi there!
as compiler I use esbuild-loader
, I can't Babel Transform @preact/signals-react-transform,
I saw that it was solved using useSignals(); in the component, I didn't like that new form or transformation, I returned to @preact/signals-react@1.3.8

greetings!
