### ISSUE TITLE
The parameter of `singal()` can be omitted, just like `useState()`. 

### ISSUE THREAD

**Issue by cnbebop** [preactjs/signals#532]
Think about this, create a issue signal, and it's initial is undefined, then you should pass `undefined` to both generic parameter and function parameter.

```ts
const issue = signal<Issue | undefined>(undefined);
```

We can see that it leads to boilerplate code and the development experience is reduced.

The `signal()` can be defiened like this:

```ts
function signal<T>(value: T): Signal<T>;
function signal<T = undefined>(): Signal<T | undefined>;
```

**Comment by XantreGodlike** [comment]
I don't think it's a problem. Better to keep function monomorphic with the same amount of arguments

**Comment by cnbebop** [comment]
> I don't think it's a problem. Better to keep function with the same amount of arguments (it's better for performance)

Even if you're right, but the class `Signal` has a optional parameter contructor, how to explain it?

**Comment by rschristian** [comment]
Looks reasonable to me, if you want to PR it.

**Comment by XantreGodlike** [comment]
> > I don't think it's a problem. Better to keep function with the same amount of arguments (it's better for performance)
> 
> Even if you're right, but the class `Signal` has an optional parameter constructor, how to explain it?
It's not for public usage. But I see, probably it will think that it can have 0 params
https://github.com/preactjs/signals/blob/58befba577d02c5cac5292fda0a599f9708e908b/packages/core/src/index.ts#L531

Anyway I think it should be benchmarked. Check for deoptimizations and how much it slows other benchmarks

**Comment by rschristian** [comment]
> Anyway I think it should be benchmarked. Check for deoptimizations and how much it slows other benchmarks

This should be a type signature-only change. There will be no effect on the benchmarks

**Comment by JoviDeCroock** [comment]
@XantreGodlike This is in relation to an already allowed paradigm, signals can be initiated with undefined or a missing initializer as you yourself link to for the `Computed.prototype`. This can't possibly affect benchmarks as it's merely a change in how the generic infers the starting value.

**Comment by XantreGodlike** [comment]
It's not we are starting to provide interface that allows different amount of args. It can cause performance slow down, depending on usage
https://jsbench.me/7slty3mtij/1
<img width="715" alt="image" src="https://github.com/preactjs/signals/assets/57757211/d498d705-77a5-441a-a066-a936aaf07760">

**Comment by XantreGodlike** [comment]
But probably impact will be insignificant

**Comment by JoviDeCroock** [comment]
Did you read my comment? It's already `?` allowed to be not there https://github.com/preactjs/signals/blob/main/packages/core/src/index.ts#L277

**Comment by XantreGodlike** [comment]
> Did you read my comment? It's already `?` allowed to be not there https://github.com/preactjs/signals/blob/main/packages/core/src/index.ts#L277

Got it. Sorry

**Comment by kidonng** [comment]
Woo-hoo, glad to see my PR #116 don't need to celebrate its 2nd birthday.
