### ISSUE TITLE
Signal values do not update in Remix with Vite integrated

### ISSUE THREAD

**Issue by rhiannonbgrant** [preactjs/signals#549]
I have used signals everywhere in my Remix app, but when I try to integrate remix with Vite, the values stop updating. Signals are so useful, please let me know how I can fix it, or if it can be fixed.

**Comment by XantreDev** [comment]
Can you provide minimal reproduction?

**Comment by rhiannonbgrant** [comment]
Hi there, I'm not quite sure exactly what the problem was but I've been updating vite, remix and signals and node to the latest stable versions and that seems to have fixed the problem which I'm so happy with. Thanks

**Comment by XantreDev** [comment]
I like when problems solves this way)

**Comment by sostenesapollo** [comment]
any idea ?

**Comment by igorbrasileiro** [comment]
Which version of remix, signals and vite are you using?
 I'm facing issues on dev mode using remix, vite and signals, even using `useSignals`
