### ISSUE TITLE
[Contribution]: Build is not works on windows and inside Github codespaces

### ISSUE THREAD

**Issue by XantreDev** [preactjs/signals#554]
`mv`, `rm -dr` - from scripts is not valid command on windows. [reference](https://github.com/preactjs/signals/blob/d3935e867646ba2628853c236c9ec7efdfc7aaee/package.json#L16)
`rm -dr` is not valid in Github codespaces either (only some of the rm flags supported in VM)

Can I make scripts cross platform to make contributions easier?

**Comment by rschristian** [comment]
Sure, we're already using `rimraf` (inconsistently) anyhow (such as the `prebuild`)

**Comment by rschristian** [comment]
Addressed in #554
