### ISSUE TITLE
useSignals not working with Astro js

### ISSUE THREAD

**Issue by ajomuch92** [preactjs/signals#565]
When you install and use this package(@preact/signals-react) on a React component, and this component is within an Astro component, doesn't work, I mean, the reactivity doesn't trigger. Do you have a workaround or can take a look?

**Comment by jesseagleboy** [comment]
Did you use an Astro directive like `client:load` on the React Component that is placed within the Astro component? The Javascript won't load without the directive.

[Template Directives](https://docs.astro.build/en/reference/directives-reference)

**Comment by ajomuch92** [comment]
Yes, I used it and doens't work

**Comment by rschristian** [comment]
Please provide a reproduction.

**Comment by XantreDev** [comment]
@ajomuch92 do you use babel plugin for signals?

**Comment by ajomuch92** [comment]
No, I'm not using that plugin. I will create a repo or sandbox to show you how is my configuration

**Comment by ajomuch92** [comment]
[Here](https://github.com/ajomuch92/test-astro-react-signals) you will find a repo with the basic configuration using Astro + React + Signals

**Comment by rschristian** [comment]
You're not calling `useSignals()` or the using the Babel plugin. Gotta use one.

Please read the docs: https://github.com/preactjs/signals/tree/main/packages/react#react-integration

**Comment by ajomuch92** [comment]
Even using `useSignal` is not working, and Astro uses esbuild instead of Babel, any idea?

**Comment by rschristian** [comment]
`useSignals()`, not `useSignal()`.
