### ISSUE TITLE
When will react19 be supported？

### ISSUE THREAD

**Issue by lyboy2012** [preactjs/signals#566]
**Describe the feature you'd love to see**
A clear and concise description of what you'd love to see added to Preact Signals.

**Additional context (optional)**

**Comment by rschristian** [comment]
What exactly isn't working?

React 19 hasn't even been released yet FWIW.

**Comment by XantreDev** [comment]
Signals will work with react 19, but probably will not with react compiler

**Comment by lyboy2012** [comment]
> What exactly isn't working?
> 
> React 19 hasn't even been released yet FWIW.

`resolve 'react' in '/Users/liying/workspace/code/car/carminiapp/node_modules/@preact/signals-react/runtime/dist'
  Parsed request is a module
  using description file: /Users/liying/workspace/code/car/carminiapp/node_modules/@preact/signals-react/runtime/package.json (relative path: ./dist)
    aliased with mapping 'react': '/Users/liying/workspace/code/car/carminiapp/node_modules/react/cjs/react.production.min.js' to '/Users/liying/workspace/code/car/carminiapp/node_modules/react/cjs/react.production.min.js'
      using description file: /Users/liying/workspace/code/car/carminiapp/node_modules/@preact/signals-react/runtime/package.json (relative path: ./dist)
        Field 'browser' doesn't contain a valid alias configuration
        root path /Users/liying/workspace/code/car/carminiapp
          using description file: /Users/liying/workspace/code/car/carminiapp/package.json (relative path: ./Users/liying/workspace/code/car/carminiapp/node_modules/react/cjs/react.production.min.js)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/liying/workspace/code/car/carminiapp/Users/liying/workspace/code/car/carminiapp/node_modules/react/cjs/react.production.min.js doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/liying/workspace/code/car/carminiapp/Users/liying/workspace/code/car/carminiapp/node_modules/react/cjs/react.production.min.js.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/liying/workspace/code/car/carminiapp/Users/liying/workspace/code/car/carminiapp/node_modules/react/cjs/react.production.min.js.jsx doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/liying/workspace/code/car/carminiapp/Users/liying/workspace/code/car/carminiapp/node_modules/react/cjs/react.production.min.js.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/liying/workspace/code/car/carminiapp/Users/liying/workspace/code/car/carminiapp/node_modules/react/cjs/react.production.min.js.tsx doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /Users/liying/workspace/code/car/carminiapp/Users/liying/workspace/code/car/carminiapp/node_modules/react/cjs/react.production.min.js.mjs doesn't exist
            .vue
              Field 'browser' doesn't contain a valid alias configuration
              /Users/liying/workspace/code/car/carminiapp/Users/liying/workspace/code/car/carminiapp/node_modules/react/cjs/react.production.min.js.vue doesn't exist
            as directory
              /Users/liying/workspace/code/car/carminiapp/Users/liying/workspace/code/car/carminiapp/node_modules/react/cjs/react.production.min.js doesn't exist
        using description file: /Users/liying/workspace/code/car/carminiapp/node_modules/react/package.json (relative path: ./cjs/react.production.min.js)
          no extension
            Field 'browser' doesn't contain a valid alias configuration
            /Users/liying/workspace/code/car/carminiapp/node_modules/react/cjs/react.production.min.js doesn't exist
          .js
            Field 'browser' doesn't contain a valid alias configuration
            /Users/liying/workspace/code/car/carminiapp/node_modules/react/cjs/react.production.min.js.js doesn't exist
          .jsx
            Field 'browser' doesn't contain a valid alias configuration
            /Users/liying/workspace/code/car/carminiapp/node_modules/react/cjs/react.production.min.js.jsx doesn't exist
          .ts
            Field 'browser' doesn't contain a valid alias configuration
            /Users/liying/workspace/code/car/carminiapp/node_modules/react/cjs/react.production.min.js.ts doesn't exist
          .tsx
            Field 'browser' doesn't contain a valid alias configuration
            /Users/liying/workspace/code/car/carminiapp/node_modules/react/cjs/react.production.min.js.tsx doesn't exist
          .mjs
            Field 'browser' doesn't contain a valid alias configuration
            /Users/liying/workspace/code/car/carminiapp/node_modules/react/cjs/react.production.min.js.mjs doesn't exist
          .vue
            Field 'browser' doesn't contain a valid alias configuration
            /Users/liying/workspace/code/car/carminiapp/node_modules/react/cjs/react.production.min.js.vue doesn't exist
          as directory
            /Users/liying/workspace/code/car/carminiapp/node_modules/react/cjs/react.production.min.js doesn't exist

→ Watching... [2024/5/24 15:25:19]

node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "[object Array]".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
`

**Comment by rschristian** [comment]
That doesn't look to be even remotely related to this repo

**Comment by rschristian** [comment]
Can you provide a reproduction?

**Comment by lyboy2012** [comment]
> Can you provide a minimal reproduction? Looks like a module resolution/bundler issue.

Thank you. Wait a minute

**Comment by XantreDev** [comment]
Your error looks more like a bundler error after updating react. I am not sure that signals make the difference

**Comment by willwillems** [comment]
> Signals will work with react 19, but probably will not with react compiler

Is there no interest long-term to make them work with the React compiler or just not right now when it's still unstable?

**Comment by rschristian** [comment]
Xantre is not a maintainer FWIW.

I wouldn't say there no interest, or that it probably wouldn't work, but I don't think we're going to maintain a fork of the compiler to add in additional logic for signals as this would be a pretty big effort. Support I believe will depend on whether it breaks signals; if not, then great! If it does, I'm not sure what we can reasonably do.

**Comment by willwillems** [comment]
For other people running into this issue, the current version of React 19 with the compiler enabled works wonderfully with signals and `module:@preact/signals-react-transform`, no need to manually use `@preact/signals-react/runtime`.

If you're not getting the reactivity you're expecting you're likely messing something else up, as was I (incorrectly structured @vitejs/plugin-react config).

Make sure you include `"module:@preact/signals-react-transform"` after `"babel-plugin-react-compiler"` and you should be good.

**Comment by mr-moon** [comment]
But, overall, what are the future of preact's memoization?

**Comment by rschristian** [comment]
@mr-moon Can you be a bit more specific?

**Comment by mr-moon** [comment]
now, after thinking of it for a moment, my question may not relate to signals, but rather preact itself. With React 19, memoization API will be replace with the compiler, yet I have not seen any news on preact's plans adopting this new paradigm or overall replacing the memoization with signals. Just thinking out loud, now that we're about to loose the memo api, will preact and/or signals follow that path.

**Comment by Nyloth9** [comment]
> If you're not getting the reactivity you're expecting you're likely messing something else up, as was I (incorrectly structured @vitejs/plugin-react config).

Can you share your vite config?
