### ISSUE TITLE
Not reactive when using with `preact-render-to-string`

### ISSUE THREAD

**Issue by sransara** [preactjs/signals#569]
- [x] Check if updating to the latest version resolves the issue

**Environment**
- [x] I am using `@preact/signals-core`
- [x] I am using `@preact/signals`

**Describe the bug**
Are signals not supposed to reactive when used with `preact-render-to-string`'s `render`?
Am I doing something wrong or is there a bug?

**To Reproduce**

https://stackblitz.com/edit/preact-starter-template-t9utmr?file=Components.tsx

I have a signal and two components that share it. Rendered with preact-render-to-string. 
The expected run time environment is the server with no hydration.

**Expected behavior**

I was expecting that when `zxcv` Image is added, `zxcv` Ref will react to it and update the value to 4.

Thank you.

**Comment by XantreDev** [comment]
Hey. What is the use case for the feature? Singnals are more about client side reactivity

**Comment by sransara** [comment]
> Signals are more about client side reactivity

Considering above, what I'm trying seems out of scope. Thank you. I'll close  this ticket.

**Comment by XantreDev** [comment]
As I see preact render to string even do not run effects. So probably it's one way renderer
https://stackblitz.com/edit/preact-starter-template-tbszme?file=Components.tsx
![image](https://github.com/preactjs/signals/assets/57757211/9b1aaa08-2a23-455a-931d-38d91de2d3ee)

**Comment by sransara** [comment]
Right. Thanks for checking. I was just reading this article: https://codewithhugo.com/react-useeffect-ssr/
and the reasoning makes sense.
