### ISSUE TITLE
Modify a signal in the constructor of root component will throw an error

### ISSUE THREAD

**Issue by xymopen** [preactjs/signals#574]
- [ ] Check if updating to the latest version resolves the issue

**Environment**
- [ ] I am using `@preact/signals-core`
- [x] I am using `@preact/signals`
- [ ] I am using `@preact/signals-react`
  - [ ] I understand usage changed in v2, and I've followed the [React Integration instructions](https://github.com/preactjs/signals/tree/chore/issue-templates/packages/react#react-integration)

```json
{
  "dependencies": {
    "@preact/signals": "^1.2.3",
    "preact": "^10.19.6",
  }
}
```

**To Reproduce**
```tsx
import { Component, render } from 'preact'
import { signal } from "@preact/signals"

const value = signal('')

export default class App extends Component {
  constructor() {
    super()

    if (value.value == '') {
      value.value = "preact"
    }
  }

  render() {
    return <input
      value={value.value}
      onInput={event => value.value = event.currentTarget.value}
    />
  }
}

render(<App />, document.getElementById('app')!)
```

**Error**: `Uncaught (in promise) TypeError: o.__ is null`

**Note**

Remove signal modification from constructor can suppress the error.

Wrap `<App />` in another component can also suppress the error.

```diff
-render(<App />, document.getElementById('app')!)
+const Wrapper = () => <App />

+render(<Wrapper />, document.getElementById('app')!)
```

**Comment by XantreDev** [comment]
I am not sure that signals support usage with class component, but certainly it shouldn't throw with such strange error

**Comment by rschristian** [comment]
> I am not sure that signals support usage with class component

We absolutely do. Unlike React, class components are first-class citizens in Preact and we've advertised their usage with signals numerous times on Twitter.

**Comment by JoviDeCroock** [comment]
Modifying state in the constructor is discouraged in general though, would be better to leverage a lifecycle for these I reckon 😅 i.e. like this https://stackblitz.com/edit/vitejs-vite-t6wyct?file=src%2Fmain.tsx,package.json,src%2Findex.css&terminal=dev

**Comment by xymopen** [comment]
I see. Feel free to close it.
