### ISSUE TITLE
@preact/signals-react-transform not working in React Native

### ISSUE THREAD

**Issue by phanthaoIT** [preactjs/signals#575]
- [ ] Check if updating to the latest version resolves the issue

**Environment**
- [ ] I am using `@preact/signals-core`
- [ ] I am using `@preact/signals`
- [X] I am using `@preact/signals-react`
  - [X] I understand usage changed in v2, and I've followed the [React Integration instructions](https://github.com/preactjs/signals/tree/chore/issue-templates/packages/react#react-integration)

**Describe the bug**
I added babel plugin but it doesn't work in React Native. it throws error: ```Cannot import useSignals outside of an ESM module file```
<img width="655" alt="image" src="https://github.com/preactjs/signals/assets/31787799/c23f7df0-be58-48de-ad07-0bfca3ed8dde">
<img width="786" alt="image" src="https://github.com/preactjs/signals/assets/31787799/d347d783-4ac5-4a26-905a-0d6d2a471f7a">

**Comment by rschristian** [comment]
Well the error is correct, you cannot use `import` outside of an ESM context.

Our export map is correct & providing the right formats, do you mean to use `require` instead?

**Comment by phanthaoIT** [comment]
Hi @rschristian, I followed the guide to add Babel transform, My project is just a React Native app but the babel  has the error```Cannot import useSignals outside of an ESM module file``` .  The signal can work but I need to add manual ```import { useSignals } from '@preact/signals-react/runtime';```. it should be works automatic

**Comment by rschristian** [comment]
> My project is just a React Native app 

We need an actual reproduction in order to help, this isn't enough to go on.

We do ship both [CJS & ESM builds](https://github.com/preactjs/signals/blob/931404e96338e120464b73e522148389e38eeb2b/packages/react-transform/package.json#L29-L35), your config may be pulling the wrong one?

**Comment by phanthaoIT** [comment]
Hi @rschristian, I think the issue is in my repo, I compile everything to CommonJS. Do you know how to signal works for this case?

**Comment by JoviDeCroock** [comment]
I reckon because you preface the babel import with `module:` it will default to import syntax, no?

**Comment by XantreDev** [comment]
I provide support of react-native in @preact-signals/safe-react
I would like to contribute this feature to the mainstream library when I will have time

**Comment by phanthaoIT** [comment]
I appreciate your support! But after I upgrade the latest version of @preact/signals-react-transform, I got the error  
![Simulator Screenshot - iPhone 11 - 2024-07-23 at 15 32 23](https://github.com/user-attachments/assets/2410371b-bab9-430f-9cc2-fb66ff641990)

**Comment by JoviDeCroock** [comment]
We need a reproduction

**Comment by URVL** [comment]
@XantreDev 

> I appreciate your support! But after I upgrade the latest version of @preact/signals-react-transform, I got the error ![Simulator Screenshot - iPhone 11 - 2024-07-23 at 15 32 23](https://private-user-images.githubusercontent.com/31787799/351255410-2410371b-bab9-430f-9cc2-fb66ff641990.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4OTcyMjcsIm5iZiI6MTcyNjg5NjkyNywicGF0aCI6Ii8zMTc4Nzc5OS8zNTEyNTU0MTAtMjQxMDM3MWItYmFiOS00MzBmLTljYzItZmI2NmZmNjQxOTkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDA1MzUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1NTZjMDEzZTczYzdiNzk3ZGE3ZDRiZmEzZWM0OTViNzQ3MWQzNTMzYWNkOGRjOWI5OWMwMWNlMjI3Njc2ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4vOmb1-kialiGvL1iLG_OKPxKddato6AjmL51k4c4pc)

I faced the same problem (it is related to babel plugin) as soon as I enable it this error appears (if I use useSignals() ) everything works.


Playback can be done simply by creating a new project and connecting signals as it is written in the documentation (and when using a signal this error appears).
npx create-expo-app DemoSignalApp --template tabs

**Comment by XantreDev** [comment]
@URVL Which version of the babel plugin do you use?

**Comment by URVL** [comment]
***@***.***/signals-react-transform": "^0.4.0",

сб, 21 сент. 2024 г. в 09:41, Valerii Smirnov ***@***.***>:

**Comment by XantreDev** [comment]
Interesting. I will try to figure out why it happens in my free time
Btw, you can try `@preact-signals/safe-react`, because I've made it especially for a react native app. It worked on the 0.72 version of react native. I hope it still works

**Comment by codeserk** [comment]
I get this and similar combination of problems, can we reopen this?

When using react 0.74+ the get the error `Cannot import useSignals outside of an ESM module file` when the version of the babel plugin is < 0.4.0

when the version of the plugin is 0.4.0, the error becomes:

```
 ERROR  RangeError: Maximum call stack size exceeded

This error is located at:
    in AppContainer
    in app(RootComponent), js engine: hermes
 ERROR  RangeError: Maximum call stack size exceeded

This error is located at:
    in AppContainer
    in app(RootComponent), js engine: hermes
 ERROR  RangeError: Maximum call stack size exceeded

This error is located at:
    in AppContainer
    in LogBox(RootComponent), js engine: hermes
 ERROR  RangeError: Maximum call stack size exceeded

This error is located at:
    in AppContainer
    in LogBox(RootComponent), js engine: hermes
```

**Comment by codeserk** [comment]
@XantreDev 
@preact-signals/safe-react seems to be working
