### ISSUE TITLE
Type 'ReadonlySignal' is not assignable to type 'ReactNode'.

### ISSUE THREAD

**Issue by pmartin-cogility** [preactjs/signals#590]
- [ ] Check if updating to the latest version resolves the issue

**Environment**
- [x] I am using `@preact/signals-core`
- [ ] I am using `@preact/signals`
- [x] I am using `@preact/signals-react`
  - [x] I understand usage changed in v2, and I've followed the [React Integration instructions](https://github.com/preactjs/signals/tree/main/packages/react#react-integration)

**Describe the bug**
Since the update to `@preact/signals-core` to `1.8.0`, I get the following error: `Type 'ReadonlySignal' is not assignable to type 'ReactNode'.` when using a signal as so...
```jsx
function Optimized() {
  // Text automatically updates without re-rendering the component:
  return <p>{count}</p>;
}
```

Forcing a downgrade to `@preact/signals-core` to `1.7.0` fixes the issue.

**Comment by JoviDeCroock** [comment]
Normally [this change](https://github.com/preactjs/signals/blob/main/packages/react/src/index.ts#L38-L45) takes care of that, do you have some override yourself to manage this or is TypeScript not recognising the import?

**Comment by pmartin-cogility** [comment]
Perhaps the issue is that "this change" for `@preact-signals/react` hasn't been released yet?

**Comment by JoviDeCroock** [comment]
😅 you are 100% correct, apologies

**Comment by pmartin-cogility** [comment]
Thank you for the amazing libraries!
