### ISSUE TITLE
Signal is not rendering JSX updates

### ISSUE THREAD

**Issue by echo292** [preactjs/signals#597]
**Environment**
Windows 10 latest updates
 "@preact/signals-react": "^2.2.0",  <--- Latest version
  "react": "^18.2.0",

**Describe the bug**
Simple button name toggling is not re-rendering JSX  updates.  

**To Reproduce**
Run this App.js code and toggle the button. Inspect the console and the the signals are toggling however JSX is not rendering the update. 

```
import { effect, signal } from '@preact/signals-react';



function App() {
  const isEditing = signal(false);

  const toggleEditing = () => {
  isEditing.value = !isEditing.value;
  console.log(isEditing.value)
};

  return (
    <div>
      <button onClick={toggleEditing}>
        {isEditing.value ? "Cancel" : "Start"}
      </button>
      <div>{isEditing.value.toString()}</div>
    </div>
  );
}

export default App;

```

**Comment by rschristian** [comment]
Have you added the babel plugin?

You also should not use `signal()` in a component, use `useSignal()` instead.

**Comment by echo292** [comment]
@rschristian Thanks! 
I ended up running version 1.2.2 with useSignal. Should this work in 2.2.0?

 "@preact/signals-react": "^1.2.2",

**Comment by rschristian** [comment]
It won't work unless you add the Babel plugin or the `useSignals()` hook in v2, no. That's why our docs say you need to use one or the other.

v1 has some edge cases and situations which our previous setup did not support, hence the changes in v2.
