### ISSUE TITLE
react, conditional rendering not working with `signal(bool)`

### ISSUE THREAD

**Issue by 2nthony** [preactjs/signals#598]
- [x] Check if updating to the latest version resolves the issue

**Environment**
- [ ] I am using `@preact/signals-core`
- [ ] I am using `@preact/signals`
- [x] I am using `@preact/signals-react`
  - [ ] I understand usage changed in v2, and I've followed the [React Integration instructions](https://github.com/preactjs/signals/tree/main/packages/react#react-integration)

**Describe the bug**
even the signal bool value changed, template not updates.

always the `closed` displayed.

```tsx
function App() {
  const open = useSignal(false);
  useSignalEffect(() => {
    console.log(open.value);
  });

  return (
    <>
      <div>open: {open.value ? 'open' : 'closed'}</div>
      <div>
        <button
          onClick={() => {
            open.value = !open.value;
          }}
        >
          toggle
        </button>
      </div>
    </>
  );
}
```

**To Reproduce**
https://stackblitz.com/edit/vitejs-vite-fp27dg?file=src%2FApp.tsx

**Comment by rschristian** [comment]
> [] I understand usage changed in v2, and I've followed the [React Integration instructions](https://github.com/preactjs/signals/tree/main/packages/react#react-integration)

We've added this to the issue template for a reason.

Please follow the [integration instructions](https://github.com/preactjs/signals/tree/main/packages/react#react-integration). You must use the `useSignals` hook or the Babe plugin in v2.
