### ISSUE TITLE
Warning: useLayoutEffect does nothing on the server

### ISSUE THREAD

**Issue by Xstoudi** [preactjs/signals#606]
- [x] Check if updating to the latest version resolves the issue

**Environment**
- [ ] I am using `@preact/signals-core`
- [ ] I am using `@preact/signals`
- [x] I am using `@preact/signals-react`
  - [x] I understand usage changed in v2, and I've followed the [React Integration instructions](https://github.com/preactjs/signals/tree/main/packages/react#react-integration)

**Describe the bug**
Hello !
When running `@preact/signals-react` on a server-side rendered inertia app, I get the following warning:
```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
```
I guess it's rather an SSR problem than an Inertia problem.

It seems to be introduced by @developit in https://github.com/preactjs/signals/commit/0bed42d71929d26ecfdc1e48a16c92a0e6280563 commit. I'm not familiar enough with the package to really know what's the best way to avoid this warning.
For now, the only workaround I found is to go back to 2.0.1 version.

Let me now if you need more informations!

**To Reproduce**
No easy way I think.

**Expected behavior**
No warning.

**Comment by rschristian** [comment]
Have you noticed any issues, or just the warning? It's possible that's just a noisy & incorrect warning that you'll have to ignore.

> To avoid this, useLayoutEffect should only be used in components that render exclusively on the client.

Strange suggestion, a key part of `useLayoutEffect` is that it doesn't run on the server, allowing you to defer work to the client, not all of which will alter the SSR'd HTML (which seems to be their goal with this warning).

**Comment by XantreDev** [comment]
It can be solved this way. I've used this approach
```ts
if (typeof window !== "undefined") useLayoutEffect(...)
```
I've used it couple times - it doesn't cause any hydration error

**Comment by JoviDeCroock** [comment]
It's generally safer to use something along the lines of

```
const useIsoMorphicEffect = typeof window === 'undefined' ? useEffect : useLayoutEffect
```

**Comment by Xstoudi** [comment]
Thanks for all your answers!

> Have you noticed any issues, or just the warning? It's possible that's just a noisy & incorrect warning that you'll have to ignore.

Only the warning, which quickly become the warningS because it get printed one time per `useSignals()` per server-rendered request. I love signals, but this is annoying enough to make me consider rewriting my components if it continues spamming.

I agree that the suggestion is lowkey useless, but I think @JoviDeCroock explanation make sense to explain why it's been made like this.

I'll do a PR and let you decide if you merge it

**Comment by rschristian** [comment]
> if React starts to run effects which they probably eventually will

Ah, fair enough. Didn't realize that was still a goal or a possible future.
