### ISSUE TITLE
Signal.value re-rendering works in versions 1.3.8, but not in version 2.

### ISSUE THREAD

**Issue by adixoo** [preactjs/signals#608]
**Environment**
node : v22.7.0
pnpm : v9.2
os : Windows 10

**Describe the bug**
```jsx
import "./App.css";
import { signal } from "@preact/signals-react";

const numbers = signal([1, 2, 3, 4, 5]);
const count = signal(0);
function App() {
   return (
      <>
         <button
            onClick={() => {
               numbers.value = [...numbers.value, numbers.value.length + 1];
               count.value = count.value + 1;
            }}
         >
            count:{count} <br /> {/* Working perfect*/}
            count.value:{count.value} {/* Not working*/}
         </button>

         {numbers.value.map((i) => ( {/* Not working*/}
            <div key={i}>{i}</div>
         ))}
      </>
   );
}

export default App;
```
When I click this button, count.value is not updating, and the list is also not updating. I used version 2.2.0(latest) of the library, but it is not working. I also checked with version 2.0.0, which is also not working, but version 1.3.8 was working.

Directly assigning `count` in the DOM works well, but I encounter a problem when I want to re-render an array of items into a list. It does not work as expected. As you know, this method follows optimization, so it won’t cause a render to this component.

**To Reproduce**
[Code](https://github.com/adixoo/preact-signals-issue).

1. Clone this repo.
2. Use `pnpm` to install.
3. Test with different versions like `@preact/signals-react@1.3.8` and `@preact/signals-react@2.0.0`.

**Expected behavior**
I know this is not the optimized way, but the problem is when I have to re-render a table, it doesn’t cause any change. It starts to behave like a variable. It must cause a re-render.

If there is any other good approach for this, that would be a good idea.

**Comment by JoviDeCroock** [comment]
There is a reason why this asks whether you read the migration guide for v2 😅 you have to either decorate with `useSignals` or use the transform.

**Comment by adixoo** [comment]
Thanks, I was confused about what was going on and why it started to behave like this. That’s why I ignored the template. I tested it on my original code, and it is working well.
