### ISSUE TITLE
transformer not working on React.memo

### ISSUE THREAD

**Issue by divyam234** [preactjs/signals#612]
Component is not transformed when its wrapped in React.memo
``signals:react-transform:skipped --------------------  { hasSignals: false, hasJSX: false } ``.

This is the debug log when component is using `React.memo`  it can't  detect jsx.

**Comment by rschristian** [comment]
Please fill out & re-add the [bug template](https://github.com/preactjs/signals/blob/main/.github/ISSUE_TEMPLATE/bug-report.md) content to your issue, it's there to allow us to help you.
