### ISSUE TITLE
How should one check for `compSig instanceof Signal` for a computed after #587?

### ISSUE THREAD

**Issue by AlexJeffcott** [preactjs/signals#613]
I would like to check to see whether a variable is a `computed`. I previously did this using `instanceof Signal` which was good enough for my purposes.

Since upgrading `preact/signals` this no longer works as `ReadonlySignal` no longer extends `Signal`.

This is [the change](https://github.com/preactjs/signals/pull/587) in question.

This is the sort of code I wrote.

```typescript
getValue(computedOrValue: ReadonlySignal<V> | V): N {
  if (computedOrValue instanceof Signal) { \\ checks is a Signal/Computed
    return computedOrValue.value
  } else {
    return computedOrValue
  }
}
```

This is the sort of code I would like to be able to write.

```typescript
getValue(computedOrValue: ReadonlySignal<V> | V): N {
  if (computedOrValue instanceof ReadonlySignal) { \\ can check is a Computed
    return computedOrValue.value
  } else {
    return computedOrValue
  }
}
```

**Comment by XantreDev** [comment]
I think you could do it like this
```ts
const Computed = computed(() => null).prototype

if (a instanceof Computed) {}
```

**Comment by XantreDev** [comment]
But actually under the hood `ReadonlySignal` still extends `Signal` and if you check `it instanceof Signal` it will return true with `ReadonlySignal`

**Comment by JoviDeCroock** [comment]
Exactly this change is only on a types level and does not affect any runtime, the type narrowing is just a bit broken in TypeScript it feels like.
