### ISSUE TITLE
React 19 Compatibility Inquiry

### ISSUE THREAD

**Issue by OsamaHIma** [preactjs/signals#625]
## React 19 Compatibility Inquiry

I'm attempting to use @preact/signals-react (v2.2.0) with React 19, but there's a peer dependency conflict.

**Current Situation:**
- @preact/signals-react version: 2.2.0
- React version: 19.0.0
- Current peer dependency constraint: "^16.14.0 || 17.x || 18.x"

**Questions/Request:**
- Are there plans to update the peer dependency to include React 19?
- Is there an upcoming version or beta release with React 19 support?
- Would you be open to broadening the peer dependency range?

**Reproduction:**
```bash
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.14.0 || 17.x || 18.x" from @preact/signals-react@2.2.0

**Comment by JoviDeCroock** [comment]
To be released soon https://github.com/preactjs/signals/pull/624
