### ISSUE TITLE
Including @preact/signals-react-transform breaks rerender on hook change for fast refresh

### ISSUE THREAD

**Issue by Artur-** [preactjs/signals#626]
- [ ] Check if updating to the latest version resolves the issue

**Environment**
- [ ] I am using `@preact/signals-core`
- [ ] I am using `@preact/signals`
- [X] I am using `@preact/signals-react`
  - [X] I understand usage changed in v2, and I've followed the [React Integration instructions](https://github.com/preactjs/signals/tree/main/packages/react#react-integration)

**Describe the bug**
React Fast Refresh has two modes of updating the view: 
1. updating the current component tree 
2. re-rendering the components from scratch

Most operations result in updating the current component tree but some operations, like adding or removing hooks, causes everything to be re-rendered and state to be lost. This is mandatory as trying to call a different number of hooks during rendering will cause React to fail with `Error: Rendered fewer hooks than expected. This may be caused by an accidental early return statement.` or `Error: Should have a queue. This is likely a bug in React. Please file an issue.` or something similar

When adding `@preact/signals-react-transform`, it seems like all operations result in trying to update to current component tree and thus modifying anything related to hooks shows one of the mentioned errors.

**To Reproduce**
https://github.com/Artur-/react-signals-hmr

1. `npm run dev`
5. Open localhost:5173
6. Click the counter a few times to change the state
7. Edit src/App.tsx and add a new `useState` hook

The `main` branch includes `@preact/signals-react-transform` and shows the problem
The `without-signals` branch shows how it is supposed to work

**Expected behavior**
The page should be updated and the counter reset to 0.
Instead, the page is empty and console contains the React error messages

**Comment by Artur-** [comment]
Without signals

https://github.com/user-attachments/assets/e62809e0-eb69-4385-a6aa-d4842575f629

With signals


https://github.com/user-attachments/assets/5bfccd1a-f4f2-443c-98b2-6f60d593cd1a

**Comment by JoviDeCroock** [comment]
Huh, that's very odd because the error message actually shows the expected behaviour.... We added a useState hook so that went from undefined --> useState and the order of the others stayed the same

**Comment by Artur-** [comment]
So I don't know how exactly fast refresh is supposed to work but debugging the code a bit, I see that on a hot update, fast refresh compares a "signature" of the old function and the new function. When the comparison succeeds, it preserves state and when there is a difference, it drops the old state.

In the plain React app, this signature is in the rewritten `App.tsx` as
```
var _s = $RefreshSig$();
...
function App() {
  _s();
...

_s(App, "8dc1Irf8dimWgWVmn2MPwBiuiBU=");
```

but when including signals, this code is no longer added to `App.tsx` at all, so no signatures are calculated and on a hot update, it runs 
```
function haveEqualSignatures(prevType, nextType) {
            var prevSignature = allSignaturesByType.get(prevType);
            var nextSignature = allSignaturesByType.get(nextType);
            if (prevSignature === void 0 && nextSignature === void 0) {
                return true;
            }
```
and as neither a "prev" or "next" signature is present, it concludes the signatures are equal and it preserves state. Apparently causing the issue

**Comment by JoviDeCroock** [comment]
I assume this is the case because we wrap it in a `try {} finally {}` it probably only analyzes the closure. https://github.com/preactjs/signals/blob/main/packages/react-transform/src/index.ts#L340-L361

**Comment by Artur-** [comment]
I tried replacing
```
const tryCatchTemplate = template.statements(_t || (_t = _`var STORE_IDENTIFIER = HOOK_IDENTIFIER(HOOK_USAGE);
try {
	BODY
} finally {
	STORE_IDENTIFIER.f();
}`));
```
with
```
const tryCatchTemplate = template.statements(_t || (_t = _`var STORE_IDENTIFIER = HOOK_IDENTIFIER(HOOK_USAGE);
	BODY
`));
```

directly in `node_modules/@preact/signals-react-transform/dist/signals-transform.mjs`

but that results in
```
Uncaught Error: Cycle detected
    at b.S (@preact_signals-react_runtime.js?v=31752f79:385:25)
    at O (@preact_signals-react_runtime.js?v=31752f79:507:21)
    at Object.S (@preact_signals-react_runtime.js?v=31752f79:566:19)
    at M (@preact_signals-react_runtime.js?v=31752f79:578:6)
    at N (@preact_signals-react_runtime.js?v=31752f79:594:15)
    at App (App.tsx:23:17)
    at renderWithHooks (chunk-QXLG2TGQ.js?v=31752f79:11594:26)
    at updateFunctionComponent (chunk-QXLG2TGQ.js?v=31752f79:14628:28)
    at beginWork (chunk-QXLG2TGQ.js?v=31752f79:15970:22)
    at HTMLUnknownElement.callCallback2 (chunk-QXLG2TGQ.js?v=31752f79:3678:22)
```

**Comment by Artur-** [comment]
It seems like there is an `experimental.noTryFinally` option already and if I enable that, then there are no cycle errors and the generated `App.tsx` looks like
```ts
function App() {
  _useSignals();
  const [count, setCount] = useState(0);
  return /* @__PURE__ */ jsxDEV(Fragment, { children: [
...
}
_c2 = App;
_c = App;
export default App;
var _c, _c2;
$RefreshReg$(_c, "App");
$RefreshReg$(_c2, "App");
```

but there are still no calls to `_s` at all and two calls to `$RefreshReg$` for the same function instead of one

**Comment by Artur-** [comment]
I dug som more and would almost like to claim that what happens is that 
1. The react refresh plugin is run, it stores the info that a `useState` hook is used in the `App` function
2. The preact transform plugin runs, it replaces the function
3. The react refresh plugin runs again, but now it has the info still stored from the first run, e.g. that a hook is called... in the original function. So it no longer works properly

**Comment by Artur-** [comment]
Because if I manually do the transform changes, like adding
```
import { useSignals as _useSignals } from "@preact/signals-react/runtime";
```
and
```
useSignals();
```
as the first statement in the `App` function, then the code is generated correctly with the expected `_s` calls

**Comment by Artur-** [comment]
That might also explain why it creates two RefreshReg calls, as it finds two functions

**Comment by JoviDeCroock** [comment]
Hmm, that's very odd... We might need to check how we can use `leave`/`enter` better to collaborate with this plugin. Not sure in all honesty 😅

**Comment by Artur-** [comment]
My first thought would have been to replace the function body and not the whole function, like
```
//  path.replaceWith(newFunction);
path.node.body = newFunction.body;
```
which actually seems to fix the immediate issue with `_s` not ending up in the source.

**Comment by Artur-** [comment]
It actually seems to work... and also when keeping the try-catch in place

**Comment by JoviDeCroock** [comment]
That's a great find, mind PR'ing it? We could see if there's any tests that start failing

**Comment by Artur-** [comment]
#628
