### ISSUE TITLE
Computed signals not working in dead-simple React component

### ISSUE THREAD

**Issue by peshoicov** [preactjs/signals#631]
I have simplified the scenario in this code playground: https://playcode.io/2199837

Basically - I have a count, which increments when I click a button ... but the computed signal never gets updated ... neither in the JSX template nor in the JS code.

Any idea if this is supposed to behave like this?

**Comment by peshoicov** [comment]
@JoviDeCroock  - OK, I will try to stick to the templates for the issues.

However - even if I use the two hooks - useSignal and useComputed - then I get the same result: https://playcode.io/2200161.

**Comment by JoviDeCroock** [comment]
You have to use 'useSignals' note the s at the end. Or the babel plugin

**Comment by peshoicov** [comment]
@JoviDeCroock  - thank you for the reply. Indeed, I haven't read the docs and went straight to a blank app to play with the signals.

However!

The reason for going this way is that I saw a super small and simple example where all worked fine out of the box.
Here is the precise moment where you can see that, in case you're curious:
https://www.youtube.com/watch?v=SO8lBVWF2Y8&t=465s

**Comment by rschristian** [comment]
@peshoicov "However", that video came out prior to v2. Knowing some users would skip the docs, we put this into the issue template to catch users who were only familiar with the v1 usage:

- [ ] I am using `@preact/signals-react`
  - [ ] I understand usage changed in v2, and I've followed the [React Integration instructions](https://github.com/preactjs/signals/tree/main/packages/react#react-integration)

Doesn't do much good when you ignore & delete it though :/

This is what frustrates maintainers, when you blow past the information we've taken the time to lay out before you and instead use a year and a half old video as a source of truth.
