### ISSUE TITLE
Migrate from version 1 – 2

### ISSUE THREAD

**Issue by nichoth** [preactjs/signals#632]
- [ ] Check if updating to the latest version resolves the issue

**Environment**
- [ ] I am using `@preact/signals-core`
- [x] I am using `@preact/signals`
- [ ] I am using `@preact/signals-react`
  - [ ] I understand usage changed in v2, and I've followed the [React Integration instructions](https://github.com/preactjs/signals/tree/main/packages/react#react-integration)

**Describe the bug**

Updating `@preact/signals` to version two throws a new error about cycle detected.

```
Uncaught Error: Cycle detected
    at ot.S (signals-core.module.js:1:3798)
    at at (signals.module.js:1:401)
    at signals.module.js:1:1526
    at signals.module.js:1:1359
    at V (preact.module.js:1:6239)
    at preact.module.js:1:9281
```
![screenshot](https://github.com/user-attachments/assets/0f3a15af-c907-4e4e-98cf-30dcf98a7c5a)

This is a deployment that demonstrates the issue: https://3e585ed9.vanishing-page.pages.dev/

[The production deploy](https://vanishing.page/), that is the same code but is working.

**Expected behavior**

Should not throw, or the new behavior should be documented.

**Comment by rschristian** [comment]
We need a minimal reproduction, not a deployed site please.

**Comment by nichoth** [comment]
I have made this demo repo. I am working on getting a more minimal code pen going.

https://github.com/nichoth/signals-reproduction

**Comment by JoviDeCroock** [comment]
Quick observation, somehow the buttons which only touch signals in their `click` callbacks are causing this. When I remove those buttons the issue goes away 🤔

**Comment by JoviDeCroock** [comment]
Hmm, there are multiple versions of signals present

```bash
❯ npm list @preact/signals-core
signals-reproduction@0.0.0 /Users/jovi/Documents/SideProjects/signals-reproduction
├─┬ @nichoth/components@0.16.15
│ └─┬ @preact/signals@1.3.1
│   └── @preact/signals-core@1.8.0 deduped
└─┬ @preact/signals@2.0.0
  └── @preact/signals-core@1.8.0
```

**Comment by nichoth** [comment]
Thank you for checking this out. That is indeed the problem. I updated the dependency to also use signals 2.0, and now it is working. Odd that it caused the "cycle detected" error, but thanks for looking into it 🙏

**Comment by JoviDeCroock** [comment]
Yes, I am not quite sure what caused the cycle detected with that but it might just be that the signal gets fed into one of the computeds/effects used in `@preact/signals` which comes from a different version which can cause some hiccups
