### ISSUE TITLE
React.StrictMode misses state update (using with ViteJS)

### ISSUE THREAD

**Issue by johot** [preactjs/signals#70]
I know this is super early days and this looks really exciting!

I tried setting up a new TypeScript + React project from scratch with ViteJS and using your counter example the first count+ click doesn't update the UI. However the second does so counter goes from 0->2->3 etc. When disabling React.StrictMode it works however. Just a heads up. Thank you for this project!

FYI: Uses React 18.2.

**Comment by clauderic** [comment]
I was able to reproduce this issue as well, though I don't think it's specific to ViteJS. Disabling `<StrictMode>` indeed fixes the issue.

Put together a small replication case here in case it helps: https://codesandbox.io/s/competent-morning-b5x6vl?file=/src/App.tsx

**Comment by GOI17** [comment]
I place an effect (from the signals-core) and logs correctly the count value but the problem is the render, for some reason ignores the first interaction with the button

**Comment by johot** [comment]
> I place an effect (from the signals-core) and logs correctly the count value but the problem is the render, for some reason ignores the first interaction with the button

Yes exactly I see the same thing :) console.log is correct but render is not. I know valtio uses snapshots (copys of the data) to make this work correctly.

**Comment by CarsonMcKinstry** [comment]
Here's a minimum reproduction of this error:

https://stackblitz.com/edit/vitejs-vite-xyi4zn
