### ISSUE TITLE
How to use with `unpkg`

### ISSUE THREAD

**Issue by HappyStriker** [preactjs/signals#77]
Hello there,

first of all: This is a great extension to Preact and just what has been missing to me to start using Preact in the first place, as the whole `Context` concept to achieve similar things seems unnecessarily complicated.

As I like to avoid using any build tools at all and since it is possible to use Preact itself just by using `import { h, Component, render } from 'https://unpkg.com/preact?module';` I am wondering how to do the same with `signals`?

The obvious solution to be would be to import it like `import { signal } from 'https://unpkg.com/@preact/signals@1.0.1/dist/signals.module.js?module';`, but this will fail, as the resource `https://unpkg.com/preact@10.10.6/hooks?module` is not available.

So is there a single, or multiple, `import` statement(s) to completely load all the required Preact tools, including `h`, `render`, `Component` as well as the new functions `signal`, `computed` etc.?

Thank you very much for your support!

Sincerly,
Happy Striker

**Comment by JoviDeCroock** [comment]
An ESM compatible bundler like esm.sh should do the trick, example https://esm.sh/@preact/signals. In the Preact repo we have an issue about this https://github.com/preactjs/preact/issues/2564
