### ISSUE TITLE
Signals don't work after HMR

### ISSUE THREAD

**Issue by divmgl** [preactjs/signals#79]
Vite `preact-ts` starter with React compat.

```tsx
import { signal } from "@preact/signals";
import { Button, css, TextField } from "@mui/material";
import { useState } from "preact/hooks";

const count = signal(0);

export function App() {
  return (
    <div className="flex">
      <Button variant="contained" onClick={() => count.value++}>
        Count {count}
      </Button>
      <TextField></TextField>
    </div>
  );
}
```
```
pnpm dev
```

Save the page, signals stop working (can't increase count).

**Comment by JoviDeCroock** [comment]
There is an issue on the prefresh repo for this

**Comment by marvinhagemeister** [comment]
Linking the issue here: https://github.com/preactjs/prefresh/issues/468

**Comment by JoviDeCroock** [comment]
Thank you @marvinhagemeister I really don't know why my copy didn't work or if I just forgot about it 😅

**Comment by JoviDeCroock** [comment]
Will release https://github.com/preactjs/prefresh/pull/469 `@prefresh/core1.4.0` later this evening which will resolve this issue! Thanks for notifying us
