### ISSUE TITLE
Control flow components

### ISSUE THREAD

**Issue by intrnl** [preactjs/signals#83]
We could optimize things a little further by adding control flow components for conditionally showing content or iterating over lists, we can use Solid as an example here.

[Solid `<Show>` tutorial](https://www.solidjs.com/tutorial/flow_show)
[Solid `<For>` tutorial](https://www.solidjs.com/tutorial/flow_for)

**Comment by rschristian** [comment]
Both are kind of the opposite of the desired direction for this, see: https://twitter.com/_developit/status/1567216573168992258

**Comment by intrnl** [comment]
I see, I suppose users can manually implement it themselves if they want to.

Closing for now!

**Comment by intrnl** [comment]
Here's for those that are interested however

https://github.com/intrnl/preact-signals-test/blob/trunk/src/app.jsx#L138-L187

I'd be a little warry about how the matching in `<Switch>` is being done though.
