### ISSUE TITLE
Extend a signal API to match the Svelte store contract

### ISSUE THREAD

**Issue by kolodziejczak-sz** [preactjs/signals#95]
First of all, thank you for the library!

I'd like to suggest a proposal to extend the usage of the `signals-core` library to the Svelte framework.
I mean an implementation of a Svelte's store contract, which is about a `subscribe` method: 
```typescript
type Subscriber<T> = (value: T) => void;
type Unsubscriber = () => void;
subscribe(run: Subscriber): Unsubscriber;
```
So, the signals would need to have an additional `subscribe` method that returns a function that lets you unsubscribe. 
The `Nanostore` library does exactly that: https://github.com/nanostores/nanostores#svelte, so developers can use `atoms` without any dedicated adapter. 
I'm sure the advantages of the ability to subscribe to a certain signal would exceed the `Svelte` support.

More info about Svelte's stores can be found here:
https://svelte.dev/docs#run-time-svelte-store
https://github.com/sveltejs/svelte/blob/master/src/runtime/store/index.ts

Thanks

**Comment by marvinhagemeister** [comment]
@kolodziejczak-sz this is a great idea! Went ahead and implemented that in https://github.com/preactjs/signals/pull/134 . Signals can be used natively with Svelte with the latest version 🎉
