### ISSUE TITLE
Data validation

### ISSUE THREAD

**Issue by oliverfindl** [preactjs/signals#97]
Hello,

thanks for your work, signals looks amazing! However, I got 1 question. While using Context API for store, user have option to validate data payload based on different actions and then mutate store or throw / log errors. How could this be achieved with signals?

E. g.: Mutate signal only if data payload is ISO 8601 date representation (YYYY-MM-DD), where date is greater than now. Should we write wrappers for validation and initialize them in each component with signal retrieved via Context API?

Thanks.

**Comment by marvinhagemeister** [comment]
> However, I got 1 question. While using Context API for store, user have option to validate data payload based on different actions and then mutate store or throw / log error

I'm not sure what you're referring to. The Context API doesn't provide such a feature. It's just a way to pass values around to nodes further down the tree. It doesn't do any sort of validation or logging logic. It sounds like you're using another third party library that deals with those concerns in your app?

Signals are merely a reactive primitive on which you can build any logic you want on top of it. In your case it sounds like you're looking for something along the lines of the following:

```ts
const date = signal<Date | null>(null);

function updateDate(value: string) {
  // Use any date library you want to validate the date
  if (!isValidISO8601Date(value)) {
    throw new Error("Not a valid ISO8061 date: " + value);
  }
  
  date.value = new Date(value);
}
```

The same pattern can be used for doing other logic like only writing to a signal if a date is greater than now, etc. Signals work best if paired with a data-driven design architecture. In that you'd define your mutation code inside functions where you validate input, before you write to the system.

I'm not sure what you mean by having to initialize wrappers for validation in each component. Generally you'd want to validate _before_ data enters your system, so that the state of your system is always guaranteed to be correct.

**Comment by oliverfindl** [comment]
Hello,

>> However, I got 1 question. While using Context API for store, user have option to validate data payload based on different actions and then mutate store or throw / log errors.
>
> I'm not sure what you're referring to. The Context API doesn't provide such a feature. It's just a way to pass values around to nodes further down the tree. It doesn't do any sort of validation or logging logic. It sounds like you're using another third party library that deals with those concerns in your app?

Sorry, I wrote this message from top of my head while still in bed... Just checked my older project, where I used such approach. I found out, that context value is set to state and dispatch function from `useReducer` hook, where you have option to perform different logic based on particular dispatched action. That's kinda different story, sorry for mystification.

Let me reword my question. Would it be possible to introduce new method similar to `effect(fn)`, which would be executed before signal update? Or if there is no re-render between signal update and effect callback (I don't know), would it be possible to provide rollback function?

> Signals are merely a reactive primitive on which you can build any logic you want on top of it. In your case it sounds like you're looking for something along the lines of the following: [code]

I had little more complex example with global state in my mind, something like this:

```typescript
// signals/index.ts

import { signal } from "@preact/signals";

export const date = signal<string | null>("2022-10-01");

export const dateErrorMessage = signal<string | null>(null);
```

```typescript
// signals/wrappers.ts

import { batch, Signal } from "@preact/signals";

const ISO_DATE_REGEXP = /^\d{4}-\d{2}-\d{2}$/;

const validateIso8601Date = (date: unknown): boolean => typeof date === "string" && ISO_DATE_REGEXP.test(date) && new Date(date) > new Date();

type UpdateFunctionOptions = {
	target: Signal;
	error?: Signal;
};

export const updateDate = (date: unknown, { target, error }: UpdateFunctionOptions): void => {
	if (!validateIso8601Date(date)) {
		const message = `Value "${date}" is not valid ISO 8601 date in future!`;

		if (error) error.value = message;
		else throw new Error(message);

		return;
	}

	batch(() => {
		if (error) error.value = null;
		target.value = date;
	});
};
```

```typescript
// main.tsx

import { createContext, render } from "preact";
import { Signal } from "@preact/signals";
import { App } from "./app";
import * as signals from "./signals";

export type ContextState = {
	signals: {
		[key: string]: Signal;
	};
};

export const AppState = createContext<ContextState>({ signals: {} });

render(
	<AppState.Provider value={{ signals }}>
		<App />
	</AppState.Provider>,
	document.getElementById("app") as HTMLElement,
);
```

```typescript
// app.tsx

import { Fragment, FunctionalComponent } from "preact";
import { useContext } from "preact/hooks";
import { AppState, ContextState } from "./main";
import { updateDate as updateDateSignalWrapper } from "./signals/wrappers";

export const App: FunctionalComponent = () => {
	const { signals } = useContext<ContextState>(AppState);

	const onClick = (event: MouseEvent | TouchEvent): void => {
		event.preventDefault();

		const date = new Date();
		date.setDate(date.getDate() + Math.floor(Math.random() * 20) + 1 - 10);

		const isoDate = date.toISOString().split("T")[0];
		console.log("Generated ISO date", isoDate);

		updateDateSignalWrapper(isoDate, {
			target: signals.date,
			error: signals.dateErrorMessage,
		});
	};

	return (
		<Fragment>
			<button type="button" className={signals.dateErrorMessage.value ? "error" : undefined} onClick={onClick}>
				{signals.date}
			</button>
			{signals.dateErrorMessage.value && <p>{signals.dateErrorMessage}</p>}
		</Fragment>
	);
};
```

With this approach you need to include your validator in every component, which needs to mutate signal and you need to pass target signal obtained from context to each validator (maybe this approach with obtaining signal from context is not required and signal can be imported directly into validator, but in signals announcement article it was used like this).

> The same pattern can be used for doing other logic like only writing to a signal if a date is greater than now, etc. Signals work best if paired with a data-driven design architecture. In that you'd define your mutation code inside functions where you validate input, before you write to the system.
>
> I'm not sure what you mean by having to initialize wrappers for validation in each component. Generally you'd want to validate before data enters your system, so that the state of your system is always guaranteed to be correct.

That's a valid point, but in this case, you have to validate data for same signal multiple times in multiple places, e. g.: user input, fetched data from API, restored from cookie / local storage, imported from user backup and so on. I personally find easier to validate data in one place - in store, before they are actually set and propagated to whole app.

I'm not here to argue, which approach is better and I completely understand if this is out of scope of this package so feel free to close this issue.

Thanks.

**Comment by marvinhagemeister** [comment]
I see where you're coming from and that it would be a convenient feature to have there. It's probably not something we're going to add natively to signals for now, but you can do this today by subclassing signal.

```js
import { Signal } from "@preact/signals";

class ValidationSignal extends Signal {
  constructor(value, validateFn) {
    super(value);
    this.validateFn = validateFn;
  }

  set value(newValue) {
    if (!this.validateFn(newValue)) {
      throw new Error("invalid");
    }
    this.value = newValue;
  }
}

// Usage:
const myDate = new ValidateSignal("");
myDate.value = validDate // works
myDate.value = invalidDate // throws
```

**Comment by oliverfindl** [comment]
Hello,

initially I had similar request in my mind (to provide validation callback as second param for signal), but I thought that param could be used for more important features in future. Extending core Signal class seems as right solution for me, not only for validation, but I can even do transformation of data (e. g.: enforce number to have only 2 decimal places). Would you mind if I publish package based on yours code provided above for such use cases?

Thanks.

**Comment by marvinhagemeister** [comment]
Sure, go ahead. The project is licensed as MIT so forks are encouraged 👍

**Comment by marvinhagemeister** [comment]
Closing this issue as there are no tasks left todo.
